%%%% This code was generated by heta-compiler of v0.6.1
% 

function [ode_func, out_func, y0_, events_conditions, events_affects] = nameless_Model(p)

    %%% auxilary
    % ternary operator
    function out = tern__(cond, x, y)
        if cond
            out = x;
        else
            out = y;
        end
    end

    ode_func = @ODEFunc;
    out_func = @OutputFunc;
    events_conditions = @Conditions;
    events_affects = {@viral_load_affect};
    y0_ = InitFunc();

    % shared variable
    shared_values = zeros(1, 91);
    integrator = [];

    %%% Initialization of dynamic records
    function y__ = InitFunc()
        integrator = []; % reset integrator
        time = 0; % zero time
        time_day = time / 24; % time_day, hours to days conversion (day)
        COVass_vpc = 0; % COVass_vpc, amount of assembled virus ready to be released from from vPC (pmole)
        vPC = 1; % vPC, concentration of vPC (Pneumocytes with virus actively replicated) in alveoli (kcell/L)
        Vol_alv = 0.014; % Vol_alv, Volume of surfactant linning alveolar surface (L)
        COVass_vpc_per_cell = p(2) * COVass_vpc / vPC / Vol_alv / p(1); % COVass_vpc_per_cell, number of COVass per vPC cell (item/cell)
        COV = 0.0018; % COV, concentration of  COV (SARS-CoV-2 virus) (pM)
        COV_RNA = 0; % COV_RNA, concentration of COV_RNA released from vPC due to their apoptosis (pM)
        COV_num_sputum_ml = p(3) * (COV + COV_RNA) * p(2) / p(28); % COV_num_sputum_ml, number of virus copies in 1 mL of sputum (item/mL)
        PC = 2.643e+9; % PC, concentration of PC type II (Pneumocytes free of virus) in alveoli (kcell/L)
        iPC = 1; % iPC, concentration of iPC (Pneumocytes with virus entered but w/o virus replication) in alveoli (kcell/L)
        PC_tot = PC + iPC + vPC; % PC_tot, total pneumocytes cell count (kcell/L)
        PC_percent = 100 * PC / PC_tot; % PC_percent, percent of PC of total pneumocytes cell count (UL)
        iPC_percent = 100 * iPC / PC_tot; % iPC_percent, percent of iPC of total pneumocytes cell count (UL)
        vPC_percent = 100 * vPC / PC_tot; % vPC_percent, percent of vPC of total pneumocytes cell count (UL)
        ACE2_pc = 615; % ACE2_pc, amount of ACE2 located at PC (pmole)
        ACE2_pc_per_cell = p(2) * ACE2_pc / PC / Vol_alv / p(1); % ACE2_pc_per_cell, number of ACE2 per PC cell (item/cell)
        COV_ACE2_pc = 0; % COV_ACE2_pc, amount of COV_ACE2 complexes located at PC (pmole)
        COV_ACE2_pc_per_cell = p(2) * COV_ACE2_pc / PC / Vol_alv / p(1); % COV_ACE2_pc_per_cell, number of COV_ACE2 per PC cell (item/cell)
        ACE2_pc_per_cell_tot = ACE2_pc_per_cell + COV_ACE2_pc_per_cell; % ACE2_pc_per_cell_tot, total number of ACE2 molecules per PC cell (item/cell)
        ACE2_ipc = 0; % ACE2_ipc, amount of ACE2 located at iPC (pmole)
        ACE2_ipc_per_cell = p(2) * ACE2_ipc / iPC / Vol_alv / p(1); % ACE2_ipc_per_cell, number of ACE2 per iPC cell (item/cell)
        COV_ACE2_ipc = 0; % COV_ACE2_ipc, amount of COV_ACE2 complexes located at iPC (pmole)
        COV_ACE2_ipc_per_cell = p(2) * COV_ACE2_ipc / iPC / Vol_alv / p(1); % COV_ACE2_ipc_per_cell, number of COV_ACE2 per iPC cell (item/cell)
        ACE2_ipc_per_cell_tot = ACE2_ipc_per_cell + COV_ACE2_ipc_per_cell; % ACE2_ipc_per_cell_tot, total number of ACE2 molecules per iPC cell (item/cell)
        ACE2_vpc = 0; % ACE2_vpc, amount of ACE2 located at vPC (pmole)
        ACE2_vpc_per_cell = p(2) * ACE2_vpc / vPC / Vol_alv / p(1); % ACE2_vpc_per_cell, number of ACE2 per vPC cell (item/cell)
        COV_ACE2_vpc = 0; % COV_ACE2_vpc, amount of COV_ACE2 complexes located at vPC (pmole)
        COV_ACE2_vpc_per_cell = p(2) * COV_ACE2_vpc / vPC / Vol_alv / p(1); % COV_ACE2_vpc_per_cell, number of COV_ACE2 per vPC cell (item/cell)
        ACE2_vpc_per_cell_tot = ACE2_vpc_per_cell + COV_ACE2_vpc_per_cell; % ACE2_vpc_per_cell_tot, total number of ACE2 molecules per vPC cell (item/cell)
        COV_pc_per_cell_tot = COV_ACE2_pc_per_cell; % COV_pc_per_cell_tot, total number of COV genomes per PC cell (item/cell)
        COV_ipc = 0; % COV_ipc, amount of partially disrupted COV particles ready to release RNA in cytoplasm located in iPC (pmole)
        COV_ipc_per_cell = p(2) * COV_ipc / iPC / Vol_alv / p(1); % COV_ipc_per_cell, number of COV per iPC cell (item/cell)
        COV_ipc_per_cell_tot = COV_ACE2_ipc_per_cell + COV_ipc_per_cell; % COV_ipc_per_cell_tot, total number of COV genomes per iPC cell (item/cell)
        COV_vpc = 0; % COV_vpc, amount of partially disrupted COV particles ready to release RNA in cytoplasm located in vPC (pmole)
        COV_vpc_per_cell = p(2) * COV_vpc / vPC / Vol_alv / p(1); % COV_vpc_per_cell, number of COV per vPC cell (item/cell)
        COV_RNA_vpc = 0; % COV_RNA_vpc, amount of COV_RNA located in vPC (pmole)
        COV_RNA_vpc_per_cell = p(2) * COV_RNA_vpc / vPC / Vol_alv / p(1); % COV_RNA_vpc_per_cell, number of COV_RNA per vPC cell (item/cell)
        COV_vpc_per_cell_tot = COV_ACE2_vpc_per_cell + COV_vpc_per_cell + COV_RNA_vpc_per_cell; % COV_vpc_per_cell_tot, total number of COV genomes per vPC cell (item/cell)
        COV_sgRNA_perc = 100 * COV_RNA / (COV + COV_RNA); % COV_sgRNA_perc, percent of actively transcribed subgenomic RNA of total (packed + unpacked) RNA in sputum samples taken from the patients (UL)
        PC_hs_ss = 2.643e+9; % PC_hs_ss, concentration of PC type II at steady state w/o virus exposure (kcell/L)
        V_mat_pc = Vol_alv * p(4) * PC_hs_ss; % V_mat_pc, influx of Pneumocytes via maturation (kcell/h)
        k_tran_pc_ipc = p(6) * COV_ACE2_pc / Vol_alv; % k_tran_pc_ipc, apparent rate constant of PC to iPC transition (1/h)
        V_tran_pc_ipc = Vol_alv * k_tran_pc_ipc * PC; % V_tran_pc_ipc, transition of Pneumocyte from normal state to state with entered COV (kcell/h)
        k_tran_ipc_vpc = p(7) * COV_ipc / Vol_alv; % k_tran_ipc_vpc, apparent rate constant of iPC to vPC transition (1/h)
        V_tran_ipc_vpc = Vol_alv * k_tran_ipc_vpc * iPC; % V_tran_ipc_vpc, transition of Pneumocyte from state with entered COV to state able to produce viral particles (kcell/h)
        V_apo_pc = Vol_alv * p(4) * PC; % V_apo_pc, apoptosis of Pneumocyte (kcell/h)
        V_apo_ipc = Vol_alv * p(4) * iPC; % V_apo_ipc, apoptosis of iPneumocyte (kcell/h)
        switch_ir = 0; % switch_ir, switch of effect of IR on vPC apoptosis (UL)
        IR_apo = 1 + switch_ir * p(23) * (time / p(21) - 1) ^ p(24) / ((1 + p(22) / p(21)) ^ p(24) + (time / p(21) - 1) ^ p(24)); % IR_apo, empiric function imitating effect of Immune Response on vPC apoptosis (UL)
        k_apo_vpc = p(5) * IR_apo; % k_apo_vpc, dependence of rate constant of vPC apoptosis on IR effect (1/h)
        V_apo_vpc = Vol_alv * k_apo_vpc * vPC; % V_apo_vpc, apoptosis of vPneumocyte (kcell/h)
        ACE2_pc_hs_ss = 615; % ACE2_pc_hs_ss, amount of ACE2 located at PC (pmole)
        k_syn_ace2_pc = p(8) * ACE2_pc_hs_ss / PC_hs_ss / p(27) / Vol_alv / p(1); % k_syn_ace2_pc, rate of ACE2 synthesis calculated per volume of PC (pM/h)
        V_syn_ace2_pc = p(27) * k_syn_ace2_pc * PC * Vol_alv * p(1); % V_syn_ace2_pc, synthesis of ACE2 by PC (pmole/h)
        V_shed_ace2_pc = p(8) * ACE2_pc; % V_shed_ace2_pc, degradation of ACE2 located at PC via shedding (pmole/h)
        steric_factor_pc = 1 - COV_ACE2_pc_per_cell / p(19); % steric_factor_pc, a term responsible for limitation of COV to cell binding; number COV molecules per cell cannot be higher than Nmax_cov_per_cell due to physical size of a cell and virus which attaches to the cell (UL)
        anti_Ab = switch_ir * p(26) * (time / p(21) - 1) ^ p(24) / ((1 + p(22) / p(21)) ^ p(24) + (time / p(21) - 1) ^ p(24)); % anti_Ab, concentration of anti-Spike attibodies (pM)
        VO = anti_Ab / (p(25) + anti_Ab); % VO, Virus Occupancy (VO) level with anti_Ab antibodies (UL)
        Kd_cov_ace2 = p(11) / p(10) / (1 - VO); % Kd_cov_ace2, apparent dissociation equilibrium constant of COV and ACE2 (pM)
        V_bind_cov_ace2_pc = p(9) * (steric_factor_pc * COV * ACE2_pc / Kd_cov_ace2 - COV_ACE2_pc); % V_bind_cov_ace2_pc, binding of COV to ACE2 located at PC surface (pmole/h)
        V_deg_ace2_apo_pc = p(4) * ACE2_pc; % V_deg_ace2_apo_pc, degradation of ACE2 located at PC via PC apoptosis (pmole/h)
        V_deg_cov_ace2_apo_pc = p(4) * COV_ACE2_pc; % V_deg_cov_ace2_apo_pc, degradation of COV_ACE2 located at PC via PC apoptosis with concomitant COV release (pmole/h)
        V_tran_ace2_pc_ipc = k_tran_pc_ipc * ACE2_pc; % V_tran_ace2_pc_ipc, transition of ACE2 from PC to iPC with transition of pneumocytes between the states (pmole/h)
        V_tran_cov_ace2_pc_ipc = k_tran_pc_ipc * COV_ACE2_pc; % V_tran_cov_ace2_pc_ipc, transition of COV_ACE2 from PC to iPC with transition of pneumocytes between the states (pmole/h)
        V_syn_ace2_ipc = p(27) * k_syn_ace2_pc * iPC * Vol_alv * p(1); % V_syn_ace2_ipc, synthesis of ACE2 by iPC (pmole/h)
        V_shed_ace2_ipc = p(8) * ACE2_ipc; % V_shed_ace2_ipc, degradation of ACE2 located at iPC via shedding (pmole/h)
        steric_factor_ipc = 1 - COV_ACE2_ipc_per_cell / p(19); % steric_factor_ipc, a term responsible for limitation of COV to cell binding; number COV molecules per cell cannot be higher than Nmax_cov_per_cell due to physical size of a cell and virus which attaches to the cell (UL)
        V_bind_cov_ace2_ipc = p(9) * (steric_factor_ipc * COV * ACE2_ipc / Kd_cov_ace2 - COV_ACE2_ipc); % V_bind_cov_ace2_ipc, binding of COV to ACE2 located at iPC surface (pmole/h)
        V_deg_ace2_apo_ipc = p(4) * ACE2_ipc; % V_deg_ace2_apo_ipc, degradation of ACE2 located at iPC via iPC apoptosis (pmole/h)
        V_deg_cov_ace2_apo_ipc = p(4) * COV_ACE2_ipc; % V_deg_cov_ace2_apo_ipc, degradation of COV_ACE2 located at iPC via iPC apoptosis with concomitant COV release (pmole/h)
        V_deg_cov_apo_ipc = p(4) * COV_ipc; % V_deg_cov_apo_ipc, degradation of COV located in iPC via iPC apoptosis (pmole/h)
        V_ent_cov_ipc = p(12) * COV_ACE2_ipc; % V_ent_cov_ipc, entry of COV into iPC with concomitant ACE2 degradation (pmole/h)
        V_tran_ace2_ipc_vpc = k_tran_ipc_vpc * ACE2_ipc; % V_tran_ace2_ipc_vpc, transition of ACE2 from iPC to vPC with transition of pneumocytes between the states (pmole/h)
        V_tran_cov_ace2_ipc_vpc = k_tran_ipc_vpc * COV_ACE2_ipc; % V_tran_cov_ace2_ipc_vpc, transition of COV_ACE2 from iPC to vPC with transition of pneumocytes between the states (pmole/h)
        V_tran_cov_ipc_vpc = k_tran_ipc_vpc * COV_ipc; % V_tran_cov_ipc_vpc, transition of COV from iPC to vPC with transition of pneumocytes between the states (pmole/h)
        V_syn_ace2_vpc = p(27) * k_syn_ace2_pc * vPC * Vol_alv * p(1); % V_syn_ace2_vpc, synthesis of ACE2 by vPC (pmole/h)
        V_shed_ace2_vpc = p(8) * ACE2_vpc; % V_shed_ace2_vpc, degradation of ACE2 located at vPC via shedding (pmole/h)
        steric_factor_vpc = 1 - COV_ACE2_vpc_per_cell / p(19); % steric_factor_vpc, a term responsible for limitation of COV to cell binding; number COV molecules per cell cannot be higher than Nmax_cov_per_cell due to physical size of a cell and virus which attaches to the cell (UL)
        V_bind_cov_ace2_vpc = p(9) * (steric_factor_vpc * COV * ACE2_vpc / Kd_cov_ace2 - COV_ACE2_vpc); % V_bind_cov_ace2_vpc, binding of COV to ACE2 located at vPC surface (pmole/h)
        V_deg_ace2_apo_vpc = k_apo_vpc * ACE2_vpc; % V_deg_ace2_apo_vpc, degradation of ACE2 located at iPC via vPC apoptosis (pmole/h)
        V_deg_cov_ace2_apo_vpc = k_apo_vpc * COV_ACE2_vpc; % V_deg_cov_ace2_apo_vpc, degradation of COV_ACE2 located at vPC via vPC apoptosis with concomitant COV release (pmole/h)
        V_ent_cov_vpc = p(12) * COV_ACE2_vpc; % V_ent_cov_vpc, entry of COV into vPC with concomitant ACE2 degradation (pmole/h)
        V_unc_cov_vpc = p(14) * COV_vpc; % V_unc_cov_vpc, uncoating of COV in vPC (pmole/h)
        V_rep_cov_rna_vpc = p(15) * COV_RNA_vpc / (1 + (COV_RNA_vpc / (vPC * Vol_alv * p(1)) / p(27)) / p(16)); % V_rep_cov_rna_vpc, replication of COV_RNA in vPC (pmole/h)
        V_ass_cov_vpc = p(17) * COV_RNA_vpc; % V_ass_cov_vpc, assembling of COV in vPC (pmole/h)
        V_rel_cov_vpc = p(13) * COVass_vpc; % V_rel_cov_vpc, release of COV in vPC (pmole/h)
        V_deg_cov_apo_vpc = k_apo_vpc * COV_vpc; % V_deg_cov_apo_vpc, degradation of COV located in vPC via vPC apoptosis (pmole/h)
        V_deg_cov_ass_apo_vpc = k_apo_vpc * COVass_vpc; % V_deg_cov_ass_apo_vpc, degradation of COVass located in vPC via vPC apoptosis with concomitant COV release (pmole/h)
        V_deg_cov_rna_apo_vpc = k_apo_vpc * COV_RNA_vpc; % V_deg_cov_rna_apo_vpc, degradation of COV_RNA located at vPC with concomitant COV_RNA release to bulk phase via vPC apoptosis (pmole/h)
        V_deg_cov = Vol_alv * p(18) * COV; % V_deg_cov, degradation of COV in bulk phase (pmole/h)
        V_deg_cov_rna = Vol_alv * p(20) * COV_RNA; % V_deg_cov_rna, degradation of COV_RNA in bulk phase (pmole/h)

        % before reinitialization
        y0__ = [switch_ir; Vol_alv; PC * Vol_alv; iPC * Vol_alv; vPC * Vol_alv; PC_hs_ss * Vol_alv; ACE2_pc; ACE2_pc_hs_ss; COV_ACE2_pc; ACE2_ipc; COV_ACE2_ipc; COV_ipc; ACE2_vpc; COV_ACE2_vpc; COV_vpc; COV_RNA_vpc; COV * Vol_alv; COV_RNA * Vol_alv; COVass_vpc];

        % reinitialization by events
        y__ = ReinitY0(time, y0__);
    end

    %%% Check events conditions at `zero`
    function y__ = ReinitY0(time, y0)
        
        cond_zero = Conditions(time, y0);
        ev_idxs = find(cond_zero==0, 1);
        
        if ~isempty(ev_idxs)
            for idx = 1:length(ev_idxs)
                ev = events_affects(idx);
                y__ = ev{1}(0.0,y0);
            end
        else
            y__ = y0;
        end
    end

    function status = OutputFunc(time, y, flag)
        switch flag
            case 'done'
                assignin('base', 'output', integrator);
            case 'affect'
                integrator(end, :) = shared_values;
            otherwise
                integrator = [integrator; shared_values];
        end
        status = 0;
    end

    function dydt = ODEFunc(time, y)

        dydt = zeros(19, 1);

        %%% Dynamic records annotation
        %1 - switch_ir, switch of effect of IR on vPC apoptosis (UL) assumed
        %2 - Vol_alv, Volume of surfactant linning alveolar surface (L) calculated as (width of linning layer)*(lunf surface area) = (0.1 - 0.3 um)*(66 - 75 m)
        %3 - PC, concentration of PC type II (Pneumocytes free of virus) in alveoli (kcell/L) calculated on the basis of total type II pneumocytes number per lungs (see ref) and volume of lung surfactant equal to 0.014L
        %4 - iPC, concentration of iPC (Pneumocytes with virus entered but w/o virus replication) in alveoli (kcell/L) 
        %5 - vPC, concentration of vPC (Pneumocytes with virus actively replicated) in alveoli (kcell/L) 
        %6 - PC_hs_ss, concentration of PC type II at steady state w/o virus exposure (kcell/L) estimate for type II pneumocytes was taken
        %7 - ACE2_pc, amount of ACE2 located at PC (pmole) based on 1e4 ACE2 per cell
        %8 - ACE2_pc_hs_ss, amount of ACE2 located at PC (pmole) based on 1e4 ACE2 per cell and total PC II number in lungs equal to 37e9 [7103258]
        %9 - COV_ACE2_pc, amount of COV_ACE2 complexes located at PC (pmole) 
        %10 - ACE2_ipc, amount of ACE2 located at iPC (pmole) 
        %11 - COV_ACE2_ipc, amount of COV_ACE2 complexes located at iPC (pmole) 
        %12 - COV_ipc, amount of partially disrupted COV particles ready to release RNA in cytoplasm located in iPC (pmole) 
        %13 - ACE2_vpc, amount of ACE2 located at vPC (pmole) 
        %14 - COV_ACE2_vpc, amount of COV_ACE2 complexes located at vPC (pmole) 
        %15 - COV_vpc, amount of partially disrupted COV particles ready to release RNA in cytoplasm located in vPC (pmole) 
        %16 - COV_RNA_vpc, amount of COV_RNA located in vPC (pmole) 
        %17 - COV, concentration of  COV (SARS-CoV-2 virus) (pM) 
        %18 - COV_RNA, concentration of COV_RNA released from vPC due to their apoptosis (pM) 
        %19 - COVass_vpc, amount of assembled virus ready to be released from from vPC (pmole) 

        %%% Output records
        % hours to days conversion (day) 
        time_day = time / 24;
        % amount of assembled virus ready to be released from from vPC (pmole) 
        COVass_vpc = y(19);
        % Volume of surfactant linning alveolar surface (L) calculated as (width of linning layer)*(lunf surface area) = (0.1 - 0.3 um)*(66 - 75 m)
        Vol_alv = y(2);
        % concentration of vPC (Pneumocytes with virus actively replicated) in alveoli (kcell/L) 
        vPC = y(5) / Vol_alv;
        % number of COVass per vPC cell (item/cell) 
        COVass_vpc_per_cell = p(2) * COVass_vpc / vPC / Vol_alv / p(1);
        % concentration of  COV (SARS-CoV-2 virus) (pM) 
        COV = y(17) / Vol_alv;
        % concentration of COV_RNA released from vPC due to their apoptosis (pM) 
        COV_RNA = y(18) / Vol_alv;
        % number of virus copies in 1 mL of sputum (item/mL) 
        COV_num_sputum_ml = p(3) * (COV + COV_RNA) * p(2) / p(28);
        % concentration of PC type II (Pneumocytes free of virus) in alveoli (kcell/L) calculated on the basis of total type II pneumocytes number per lungs (see ref) and volume of lung surfactant equal to 0.014L
        PC = y(3) / Vol_alv;
        % concentration of iPC (Pneumocytes with virus entered but w/o virus replication) in alveoli (kcell/L) 
        iPC = y(4) / Vol_alv;
        % total pneumocytes cell count (kcell/L) 
        PC_tot = PC + iPC + vPC;
        % percent of PC of total pneumocytes cell count (UL) 
        PC_percent = 100 * PC / PC_tot;
        % percent of iPC of total pneumocytes cell count (UL) 
        iPC_percent = 100 * iPC / PC_tot;
        % percent of vPC of total pneumocytes cell count (UL) 
        vPC_percent = 100 * vPC / PC_tot;
        % amount of ACE2 located at PC (pmole) based on 1e4 ACE2 per cell
        ACE2_pc = y(7);
        % number of ACE2 per PC cell (item/cell) 
        ACE2_pc_per_cell = p(2) * ACE2_pc / PC / Vol_alv / p(1);
        % amount of COV_ACE2 complexes located at PC (pmole) 
        COV_ACE2_pc = y(9);
        % number of COV_ACE2 per PC cell (item/cell) 
        COV_ACE2_pc_per_cell = p(2) * COV_ACE2_pc / PC / Vol_alv / p(1);
        % total number of ACE2 molecules per PC cell (item/cell) 
        ACE2_pc_per_cell_tot = ACE2_pc_per_cell + COV_ACE2_pc_per_cell;
        % amount of ACE2 located at iPC (pmole) 
        ACE2_ipc = y(10);
        % number of ACE2 per iPC cell (item/cell) 
        ACE2_ipc_per_cell = p(2) * ACE2_ipc / iPC / Vol_alv / p(1);
        % amount of COV_ACE2 complexes located at iPC (pmole) 
        COV_ACE2_ipc = y(11);
        % number of COV_ACE2 per iPC cell (item/cell) 
        COV_ACE2_ipc_per_cell = p(2) * COV_ACE2_ipc / iPC / Vol_alv / p(1);
        % total number of ACE2 molecules per iPC cell (item/cell) 
        ACE2_ipc_per_cell_tot = ACE2_ipc_per_cell + COV_ACE2_ipc_per_cell;
        % amount of ACE2 located at vPC (pmole) 
        ACE2_vpc = y(13);
        % number of ACE2 per vPC cell (item/cell) 
        ACE2_vpc_per_cell = p(2) * ACE2_vpc / vPC / Vol_alv / p(1);
        % amount of COV_ACE2 complexes located at vPC (pmole) 
        COV_ACE2_vpc = y(14);
        % number of COV_ACE2 per vPC cell (item/cell) 
        COV_ACE2_vpc_per_cell = p(2) * COV_ACE2_vpc / vPC / Vol_alv / p(1);
        % total number of ACE2 molecules per vPC cell (item/cell) 
        ACE2_vpc_per_cell_tot = ACE2_vpc_per_cell + COV_ACE2_vpc_per_cell;
        % total number of COV genomes per PC cell (item/cell) 
        COV_pc_per_cell_tot = COV_ACE2_pc_per_cell;
        % amount of partially disrupted COV particles ready to release RNA in cytoplasm located in iPC (pmole) 
        COV_ipc = y(12);
        % number of COV per iPC cell (item/cell) 
        COV_ipc_per_cell = p(2) * COV_ipc / iPC / Vol_alv / p(1);
        % total number of COV genomes per iPC cell (item/cell) 
        COV_ipc_per_cell_tot = COV_ACE2_ipc_per_cell + COV_ipc_per_cell;
        % amount of partially disrupted COV particles ready to release RNA in cytoplasm located in vPC (pmole) 
        COV_vpc = y(15);
        % number of COV per vPC cell (item/cell) 
        COV_vpc_per_cell = p(2) * COV_vpc / vPC / Vol_alv / p(1);
        % amount of COV_RNA located in vPC (pmole) 
        COV_RNA_vpc = y(16);
        % number of COV_RNA per vPC cell (item/cell) 
        COV_RNA_vpc_per_cell = p(2) * COV_RNA_vpc / vPC / Vol_alv / p(1);
        % total number of COV genomes per vPC cell (item/cell) 
        COV_vpc_per_cell_tot = COV_ACE2_vpc_per_cell + COV_vpc_per_cell + COV_RNA_vpc_per_cell;
        % percent of actively transcribed subgenomic RNA of total (packed + unpacked) RNA in sputum samples taken from the patients (UL) 
        COV_sgRNA_perc = 100 * COV_RNA / (COV + COV_RNA);
        % concentration of PC type II at steady state w/o virus exposure (kcell/L) estimate for type II pneumocytes was taken
        PC_hs_ss = y(6) / Vol_alv;
        % influx of Pneumocytes via maturation (kcell/h) 
        V_mat_pc = Vol_alv * p(4) * PC_hs_ss;
        % apparent rate constant of PC to iPC transition (1/h) 
        k_tran_pc_ipc = p(6) * COV_ACE2_pc / Vol_alv;
        % transition of Pneumocyte from normal state to state with entered COV (kcell/h) 
        V_tran_pc_ipc = Vol_alv * k_tran_pc_ipc * PC;
        % apparent rate constant of iPC to vPC transition (1/h) 
        k_tran_ipc_vpc = p(7) * COV_ipc / Vol_alv;
        % transition of Pneumocyte from state with entered COV to state able to produce viral particles (kcell/h) 
        V_tran_ipc_vpc = Vol_alv * k_tran_ipc_vpc * iPC;
        % apoptosis of Pneumocyte (kcell/h) 
        V_apo_pc = Vol_alv * p(4) * PC;
        % apoptosis of iPneumocyte (kcell/h) 
        V_apo_ipc = Vol_alv * p(4) * iPC;
        % switch of effect of IR on vPC apoptosis (UL) assumed
        switch_ir = y(1);
        % empiric function imitating effect of Immune Response on vPC apoptosis (UL) 
        IR_apo = 1 + switch_ir * p(23) * (time / p(21) - 1) ^ p(24) / ((1 + p(22) / p(21)) ^ p(24) + (time / p(21) - 1) ^ p(24));
        % dependence of rate constant of vPC apoptosis on IR effect (1/h) 
        k_apo_vpc = p(5) * IR_apo;
        % apoptosis of vPneumocyte (kcell/h) 
        V_apo_vpc = Vol_alv * k_apo_vpc * vPC;
        % amount of ACE2 located at PC (pmole) based on 1e4 ACE2 per cell and total PC II number in lungs equal to 37e9 [7103258]
        ACE2_pc_hs_ss = y(8);
        % rate of ACE2 synthesis calculated per volume of PC (pM/h) 
        k_syn_ace2_pc = p(8) * ACE2_pc_hs_ss / PC_hs_ss / p(27) / Vol_alv / p(1);
        % synthesis of ACE2 by PC (pmole/h) 
        V_syn_ace2_pc = p(27) * k_syn_ace2_pc * PC * Vol_alv * p(1);
        % degradation of ACE2 located at PC via shedding (pmole/h) 
        V_shed_ace2_pc = p(8) * ACE2_pc;
        % a term responsible for limitation of COV to cell binding; number COV molecules per cell cannot be higher than Nmax_cov_per_cell due to physical size of a cell and virus which attaches to the cell (UL) 
        steric_factor_pc = 1 - COV_ACE2_pc_per_cell / p(19);
        % concentration of anti-Spike attibodies (pM) hill like expression describes general kinetic pattern observed for Spike specific IgG and IgM in [32350462]
        anti_Ab = switch_ir * p(26) * (time / p(21) - 1) ^ p(24) / ((1 + p(22) / p(21)) ^ p(24) + (time / p(21) - 1) ^ p(24));
        % Virus Occupancy (VO) level with anti_Ab antibodies (UL) 
        VO = anti_Ab / (p(25) + anti_Ab);
        % apparent dissociation equilibrium constant of COV and ACE2 (pM) Kd for viral Spike receptor binding domain (RBD) and ACE2 receptor is known and equal to 4.67 nM. Basing on estimate that virion includes  VO*Num_sp_per_cov free spike proteins ready to bind to ACE2 we have come to the equation for apparent Kd describing binding of virion and ACE2
        Kd_cov_ace2 = p(11) / p(10) / (1 - VO);
        % binding of COV to ACE2 located at PC surface (pmole/h) 
        V_bind_cov_ace2_pc = p(9) * (steric_factor_pc * COV * ACE2_pc / Kd_cov_ace2 - COV_ACE2_pc);
        % degradation of ACE2 located at PC via PC apoptosis (pmole/h) 
        V_deg_ace2_apo_pc = p(4) * ACE2_pc;
        % degradation of COV_ACE2 located at PC via PC apoptosis with concomitant COV release (pmole/h) 
        V_deg_cov_ace2_apo_pc = p(4) * COV_ACE2_pc;
        % transition of ACE2 from PC to iPC with transition of pneumocytes between the states (pmole/h) 
        V_tran_ace2_pc_ipc = k_tran_pc_ipc * ACE2_pc;
        % transition of COV_ACE2 from PC to iPC with transition of pneumocytes between the states (pmole/h) 
        V_tran_cov_ace2_pc_ipc = k_tran_pc_ipc * COV_ACE2_pc;
        % synthesis of ACE2 by iPC (pmole/h) 
        V_syn_ace2_ipc = p(27) * k_syn_ace2_pc * iPC * Vol_alv * p(1);
        % degradation of ACE2 located at iPC via shedding (pmole/h) 
        V_shed_ace2_ipc = p(8) * ACE2_ipc;
        % a term responsible for limitation of COV to cell binding; number COV molecules per cell cannot be higher than Nmax_cov_per_cell due to physical size of a cell and virus which attaches to the cell (UL) 
        steric_factor_ipc = 1 - COV_ACE2_ipc_per_cell / p(19);
        % binding of COV to ACE2 located at iPC surface (pmole/h) 
        V_bind_cov_ace2_ipc = p(9) * (steric_factor_ipc * COV * ACE2_ipc / Kd_cov_ace2 - COV_ACE2_ipc);
        % degradation of ACE2 located at iPC via iPC apoptosis (pmole/h) 
        V_deg_ace2_apo_ipc = p(4) * ACE2_ipc;
        % degradation of COV_ACE2 located at iPC via iPC apoptosis with concomitant COV release (pmole/h) 
        V_deg_cov_ace2_apo_ipc = p(4) * COV_ACE2_ipc;
        % degradation of COV located in iPC via iPC apoptosis (pmole/h) 
        V_deg_cov_apo_ipc = p(4) * COV_ipc;
        % entry of COV into iPC with concomitant ACE2 degradation (pmole/h) 
        V_ent_cov_ipc = p(12) * COV_ACE2_ipc;
        % transition of ACE2 from iPC to vPC with transition of pneumocytes between the states (pmole/h) 
        V_tran_ace2_ipc_vpc = k_tran_ipc_vpc * ACE2_ipc;
        % transition of COV_ACE2 from iPC to vPC with transition of pneumocytes between the states (pmole/h) 
        V_tran_cov_ace2_ipc_vpc = k_tran_ipc_vpc * COV_ACE2_ipc;
        % transition of COV from iPC to vPC with transition of pneumocytes between the states (pmole/h) 
        V_tran_cov_ipc_vpc = k_tran_ipc_vpc * COV_ipc;
        % synthesis of ACE2 by vPC (pmole/h) 
        V_syn_ace2_vpc = p(27) * k_syn_ace2_pc * vPC * Vol_alv * p(1);
        % degradation of ACE2 located at vPC via shedding (pmole/h) 
        V_shed_ace2_vpc = p(8) * ACE2_vpc;
        % a term responsible for limitation of COV to cell binding; number COV molecules per cell cannot be higher than Nmax_cov_per_cell due to physical size of a cell and virus which attaches to the cell (UL) 
        steric_factor_vpc = 1 - COV_ACE2_vpc_per_cell / p(19);
        % binding of COV to ACE2 located at vPC surface (pmole/h) 
        V_bind_cov_ace2_vpc = p(9) * (steric_factor_vpc * COV * ACE2_vpc / Kd_cov_ace2 - COV_ACE2_vpc);
        % degradation of ACE2 located at iPC via vPC apoptosis (pmole/h) 
        V_deg_ace2_apo_vpc = k_apo_vpc * ACE2_vpc;
        % degradation of COV_ACE2 located at vPC via vPC apoptosis with concomitant COV release (pmole/h) 
        V_deg_cov_ace2_apo_vpc = k_apo_vpc * COV_ACE2_vpc;
        % entry of COV into vPC with concomitant ACE2 degradation (pmole/h) 
        V_ent_cov_vpc = p(12) * COV_ACE2_vpc;
        % uncoating of COV in vPC (pmole/h) 
        V_unc_cov_vpc = p(14) * COV_vpc;
        % replication of COV_RNA in vPC (pmole/h) 
        V_rep_cov_rna_vpc = p(15) * COV_RNA_vpc / (1 + (COV_RNA_vpc / (vPC * Vol_alv * p(1)) / p(27)) / p(16));
        % assembling of COV in vPC (pmole/h) 
        V_ass_cov_vpc = p(17) * COV_RNA_vpc;
        % release of COV in vPC (pmole/h) 
        V_rel_cov_vpc = p(13) * COVass_vpc;
        % degradation of COV located in vPC via vPC apoptosis (pmole/h) 
        V_deg_cov_apo_vpc = k_apo_vpc * COV_vpc;
        % degradation of COVass located in vPC via vPC apoptosis with concomitant COV release (pmole/h) 
        V_deg_cov_ass_apo_vpc = k_apo_vpc * COVass_vpc;
        % degradation of COV_RNA located at vPC with concomitant COV_RNA release to bulk phase via vPC apoptosis (pmole/h) 
        V_deg_cov_rna_apo_vpc = k_apo_vpc * COV_RNA_vpc;
        % degradation of COV in bulk phase (pmole/h) 
        V_deg_cov = Vol_alv * p(18) * COV;
        % degradation of COV_RNA in bulk phase (pmole/h) 
        V_deg_cov_rna = Vol_alv * p(20) * COV_RNA;
        shared_values = [time_day, COVass_vpc, Vol_alv, vPC, COVass_vpc_per_cell, COV, COV_RNA, COV_num_sputum_ml, PC, iPC, PC_tot, PC_percent, iPC_percent, vPC_percent, ACE2_pc, ACE2_pc_per_cell, COV_ACE2_pc, COV_ACE2_pc_per_cell, ACE2_pc_per_cell_tot, ACE2_ipc, ACE2_ipc_per_cell, COV_ACE2_ipc, COV_ACE2_ipc_per_cell, ACE2_ipc_per_cell_tot, ACE2_vpc, ACE2_vpc_per_cell, COV_ACE2_vpc, COV_ACE2_vpc_per_cell, ACE2_vpc_per_cell_tot, COV_pc_per_cell_tot, COV_ipc, COV_ipc_per_cell, COV_ipc_per_cell_tot, COV_vpc, COV_vpc_per_cell, COV_RNA_vpc, COV_RNA_vpc_per_cell, COV_vpc_per_cell_tot, COV_sgRNA_perc, PC_hs_ss, V_mat_pc, k_tran_pc_ipc, V_tran_pc_ipc, k_tran_ipc_vpc, V_tran_ipc_vpc, V_apo_pc, V_apo_ipc, switch_ir, IR_apo, k_apo_vpc, V_apo_vpc, ACE2_pc_hs_ss, k_syn_ace2_pc, V_syn_ace2_pc, V_shed_ace2_pc, steric_factor_pc, anti_Ab, VO, Kd_cov_ace2, V_bind_cov_ace2_pc, V_deg_ace2_apo_pc, V_deg_cov_ace2_apo_pc, V_tran_ace2_pc_ipc, V_tran_cov_ace2_pc_ipc, V_syn_ace2_ipc, V_shed_ace2_ipc, steric_factor_ipc, V_bind_cov_ace2_ipc, V_deg_ace2_apo_ipc, V_deg_cov_ace2_apo_ipc, V_deg_cov_apo_ipc, V_ent_cov_ipc, V_tran_ace2_ipc_vpc, V_tran_cov_ace2_ipc_vpc, V_tran_cov_ipc_vpc, V_syn_ace2_vpc, V_shed_ace2_vpc, steric_factor_vpc, V_bind_cov_ace2_vpc, V_deg_ace2_apo_vpc, V_deg_cov_ace2_apo_vpc, V_ent_cov_vpc, V_unc_cov_vpc, V_rep_cov_rna_vpc, V_ass_cov_vpc, V_rel_cov_vpc, V_deg_cov_apo_vpc, V_deg_cov_ass_apo_vpc, V_deg_cov_rna_apo_vpc, V_deg_cov, V_deg_cov_rna];

        %%% Differential equations
        dydt(1) = 0;
        dydt(2) = 0;
        dydt(3) = V_mat_pc -V_tran_pc_ipc -V_apo_pc;
        dydt(4) = V_tran_pc_ipc -V_tran_ipc_vpc -V_apo_ipc;
        dydt(5) = V_tran_ipc_vpc -V_apo_vpc;
        dydt(6) = 0;
        dydt(7) = V_syn_ace2_pc -V_shed_ace2_pc -V_bind_cov_ace2_pc -V_deg_ace2_apo_pc -V_tran_ace2_pc_ipc;
        dydt(8) = 0;
        dydt(9) = V_bind_cov_ace2_pc -V_deg_cov_ace2_apo_pc -V_tran_cov_ace2_pc_ipc;
        dydt(10) = V_tran_ace2_pc_ipc +V_syn_ace2_ipc -V_shed_ace2_ipc -V_bind_cov_ace2_ipc -V_deg_ace2_apo_ipc -V_tran_ace2_ipc_vpc;
        dydt(11) = V_tran_cov_ace2_pc_ipc +V_bind_cov_ace2_ipc -V_deg_cov_ace2_apo_ipc -V_ent_cov_ipc -V_tran_cov_ace2_ipc_vpc;
        dydt(12) = -V_deg_cov_apo_ipc +V_ent_cov_ipc -V_tran_cov_ipc_vpc;
        dydt(13) = V_tran_ace2_ipc_vpc +V_syn_ace2_vpc -V_shed_ace2_vpc -V_bind_cov_ace2_vpc -V_deg_ace2_apo_vpc;
        dydt(14) = V_tran_cov_ace2_ipc_vpc +V_bind_cov_ace2_vpc -V_deg_cov_ace2_apo_vpc -V_ent_cov_vpc;
        dydt(15) = V_tran_cov_ipc_vpc +V_ent_cov_vpc -V_unc_cov_vpc -V_deg_cov_apo_vpc;
        dydt(16) = V_unc_cov_vpc +V_rep_cov_rna_vpc -V_ass_cov_vpc -V_deg_cov_rna_apo_vpc;
        dydt(17) = -V_bind_cov_ace2_pc +V_deg_cov_ace2_apo_pc -V_bind_cov_ace2_ipc +V_deg_cov_ace2_apo_ipc -V_bind_cov_ace2_vpc +V_deg_cov_ace2_apo_vpc +V_rel_cov_vpc +V_deg_cov_ass_apo_vpc -V_deg_cov;
        dydt(18) = V_deg_cov_rna_apo_vpc -V_deg_cov_rna;
        dydt(19) = V_ass_cov_vpc -V_rel_cov_vpc -V_deg_cov_ass_apo_vpc;
    end

    
    function res = viral_load_condition(time, y)

        res = time - p(21);
    end
    function y = viral_load_affect(time, y)

        %%% Records
        % hours to days conversion (day) 
        time_day = time / 24;
        % amount of assembled virus ready to be released from from vPC (pmole) 
        COVass_vpc = y(19);
        % Volume of surfactant linning alveolar surface (L) calculated as (width of linning layer)*(lunf surface area) = (0.1 - 0.3 um)*(66 - 75 m)
        Vol_alv = y(2);
        % concentration of vPC (Pneumocytes with virus actively replicated) in alveoli (kcell/L) 
        vPC = y(5) / Vol_alv;
        % number of COVass per vPC cell (item/cell) 
        COVass_vpc_per_cell = p(2) * COVass_vpc / vPC / Vol_alv / p(1);
        % concentration of  COV (SARS-CoV-2 virus) (pM) 
        COV = y(17) / Vol_alv;
        % concentration of COV_RNA released from vPC due to their apoptosis (pM) 
        COV_RNA = y(18) / Vol_alv;
        % number of virus copies in 1 mL of sputum (item/mL) 
        COV_num_sputum_ml = p(3) * (COV + COV_RNA) * p(2) / p(28);
        % concentration of PC type II (Pneumocytes free of virus) in alveoli (kcell/L) calculated on the basis of total type II pneumocytes number per lungs (see ref) and volume of lung surfactant equal to 0.014L
        PC = y(3) / Vol_alv;
        % concentration of iPC (Pneumocytes with virus entered but w/o virus replication) in alveoli (kcell/L) 
        iPC = y(4) / Vol_alv;
        % total pneumocytes cell count (kcell/L) 
        PC_tot = PC + iPC + vPC;
        % percent of PC of total pneumocytes cell count (UL) 
        PC_percent = 100 * PC / PC_tot;
        % percent of iPC of total pneumocytes cell count (UL) 
        iPC_percent = 100 * iPC / PC_tot;
        % percent of vPC of total pneumocytes cell count (UL) 
        vPC_percent = 100 * vPC / PC_tot;
        % amount of ACE2 located at PC (pmole) based on 1e4 ACE2 per cell
        ACE2_pc = y(7);
        % number of ACE2 per PC cell (item/cell) 
        ACE2_pc_per_cell = p(2) * ACE2_pc / PC / Vol_alv / p(1);
        % amount of COV_ACE2 complexes located at PC (pmole) 
        COV_ACE2_pc = y(9);
        % number of COV_ACE2 per PC cell (item/cell) 
        COV_ACE2_pc_per_cell = p(2) * COV_ACE2_pc / PC / Vol_alv / p(1);
        % total number of ACE2 molecules per PC cell (item/cell) 
        ACE2_pc_per_cell_tot = ACE2_pc_per_cell + COV_ACE2_pc_per_cell;
        % amount of ACE2 located at iPC (pmole) 
        ACE2_ipc = y(10);
        % number of ACE2 per iPC cell (item/cell) 
        ACE2_ipc_per_cell = p(2) * ACE2_ipc / iPC / Vol_alv / p(1);
        % amount of COV_ACE2 complexes located at iPC (pmole) 
        COV_ACE2_ipc = y(11);
        % number of COV_ACE2 per iPC cell (item/cell) 
        COV_ACE2_ipc_per_cell = p(2) * COV_ACE2_ipc / iPC / Vol_alv / p(1);
        % total number of ACE2 molecules per iPC cell (item/cell) 
        ACE2_ipc_per_cell_tot = ACE2_ipc_per_cell + COV_ACE2_ipc_per_cell;
        % amount of ACE2 located at vPC (pmole) 
        ACE2_vpc = y(13);
        % number of ACE2 per vPC cell (item/cell) 
        ACE2_vpc_per_cell = p(2) * ACE2_vpc / vPC / Vol_alv / p(1);
        % amount of COV_ACE2 complexes located at vPC (pmole) 
        COV_ACE2_vpc = y(14);
        % number of COV_ACE2 per vPC cell (item/cell) 
        COV_ACE2_vpc_per_cell = p(2) * COV_ACE2_vpc / vPC / Vol_alv / p(1);
        % total number of ACE2 molecules per vPC cell (item/cell) 
        ACE2_vpc_per_cell_tot = ACE2_vpc_per_cell + COV_ACE2_vpc_per_cell;
        % total number of COV genomes per PC cell (item/cell) 
        COV_pc_per_cell_tot = COV_ACE2_pc_per_cell;
        % amount of partially disrupted COV particles ready to release RNA in cytoplasm located in iPC (pmole) 
        COV_ipc = y(12);
        % number of COV per iPC cell (item/cell) 
        COV_ipc_per_cell = p(2) * COV_ipc / iPC / Vol_alv / p(1);
        % total number of COV genomes per iPC cell (item/cell) 
        COV_ipc_per_cell_tot = COV_ACE2_ipc_per_cell + COV_ipc_per_cell;
        % amount of partially disrupted COV particles ready to release RNA in cytoplasm located in vPC (pmole) 
        COV_vpc = y(15);
        % number of COV per vPC cell (item/cell) 
        COV_vpc_per_cell = p(2) * COV_vpc / vPC / Vol_alv / p(1);
        % amount of COV_RNA located in vPC (pmole) 
        COV_RNA_vpc = y(16);
        % number of COV_RNA per vPC cell (item/cell) 
        COV_RNA_vpc_per_cell = p(2) * COV_RNA_vpc / vPC / Vol_alv / p(1);
        % total number of COV genomes per vPC cell (item/cell) 
        COV_vpc_per_cell_tot = COV_ACE2_vpc_per_cell + COV_vpc_per_cell + COV_RNA_vpc_per_cell;
        % percent of actively transcribed subgenomic RNA of total (packed + unpacked) RNA in sputum samples taken from the patients (UL) 
        COV_sgRNA_perc = 100 * COV_RNA / (COV + COV_RNA);
        % concentration of PC type II at steady state w/o virus exposure (kcell/L) estimate for type II pneumocytes was taken
        PC_hs_ss = y(6) / Vol_alv;
        % influx of Pneumocytes via maturation (kcell/h) 
        V_mat_pc = Vol_alv * p(4) * PC_hs_ss;
        % apparent rate constant of PC to iPC transition (1/h) 
        k_tran_pc_ipc = p(6) * COV_ACE2_pc / Vol_alv;
        % transition of Pneumocyte from normal state to state with entered COV (kcell/h) 
        V_tran_pc_ipc = Vol_alv * k_tran_pc_ipc * PC;
        % apparent rate constant of iPC to vPC transition (1/h) 
        k_tran_ipc_vpc = p(7) * COV_ipc / Vol_alv;
        % transition of Pneumocyte from state with entered COV to state able to produce viral particles (kcell/h) 
        V_tran_ipc_vpc = Vol_alv * k_tran_ipc_vpc * iPC;
        % apoptosis of Pneumocyte (kcell/h) 
        V_apo_pc = Vol_alv * p(4) * PC;
        % apoptosis of iPneumocyte (kcell/h) 
        V_apo_ipc = Vol_alv * p(4) * iPC;
        % switch of effect of IR on vPC apoptosis (UL) assumed
        switch_ir = y(1);
        % empiric function imitating effect of Immune Response on vPC apoptosis (UL) 
        IR_apo = 1 + switch_ir * p(23) * (time / p(21) - 1) ^ p(24) / ((1 + p(22) / p(21)) ^ p(24) + (time / p(21) - 1) ^ p(24));
        % dependence of rate constant of vPC apoptosis on IR effect (1/h) 
        k_apo_vpc = p(5) * IR_apo;
        % apoptosis of vPneumocyte (kcell/h) 
        V_apo_vpc = Vol_alv * k_apo_vpc * vPC;
        % amount of ACE2 located at PC (pmole) based on 1e4 ACE2 per cell and total PC II number in lungs equal to 37e9 [7103258]
        ACE2_pc_hs_ss = y(8);
        % rate of ACE2 synthesis calculated per volume of PC (pM/h) 
        k_syn_ace2_pc = p(8) * ACE2_pc_hs_ss / PC_hs_ss / p(27) / Vol_alv / p(1);
        % synthesis of ACE2 by PC (pmole/h) 
        V_syn_ace2_pc = p(27) * k_syn_ace2_pc * PC * Vol_alv * p(1);
        % degradation of ACE2 located at PC via shedding (pmole/h) 
        V_shed_ace2_pc = p(8) * ACE2_pc;
        % a term responsible for limitation of COV to cell binding; number COV molecules per cell cannot be higher than Nmax_cov_per_cell due to physical size of a cell and virus which attaches to the cell (UL) 
        steric_factor_pc = 1 - COV_ACE2_pc_per_cell / p(19);
        % concentration of anti-Spike attibodies (pM) hill like expression describes general kinetic pattern observed for Spike specific IgG and IgM in [32350462]
        anti_Ab = switch_ir * p(26) * (time / p(21) - 1) ^ p(24) / ((1 + p(22) / p(21)) ^ p(24) + (time / p(21) - 1) ^ p(24));
        % Virus Occupancy (VO) level with anti_Ab antibodies (UL) 
        VO = anti_Ab / (p(25) + anti_Ab);
        % apparent dissociation equilibrium constant of COV and ACE2 (pM) Kd for viral Spike receptor binding domain (RBD) and ACE2 receptor is known and equal to 4.67 nM. Basing on estimate that virion includes  VO*Num_sp_per_cov free spike proteins ready to bind to ACE2 we have come to the equation for apparent Kd describing binding of virion and ACE2
        Kd_cov_ace2 = p(11) / p(10) / (1 - VO);
        % binding of COV to ACE2 located at PC surface (pmole/h) 
        V_bind_cov_ace2_pc = p(9) * (steric_factor_pc * COV * ACE2_pc / Kd_cov_ace2 - COV_ACE2_pc);
        % degradation of ACE2 located at PC via PC apoptosis (pmole/h) 
        V_deg_ace2_apo_pc = p(4) * ACE2_pc;
        % degradation of COV_ACE2 located at PC via PC apoptosis with concomitant COV release (pmole/h) 
        V_deg_cov_ace2_apo_pc = p(4) * COV_ACE2_pc;
        % transition of ACE2 from PC to iPC with transition of pneumocytes between the states (pmole/h) 
        V_tran_ace2_pc_ipc = k_tran_pc_ipc * ACE2_pc;
        % transition of COV_ACE2 from PC to iPC with transition of pneumocytes between the states (pmole/h) 
        V_tran_cov_ace2_pc_ipc = k_tran_pc_ipc * COV_ACE2_pc;
        % synthesis of ACE2 by iPC (pmole/h) 
        V_syn_ace2_ipc = p(27) * k_syn_ace2_pc * iPC * Vol_alv * p(1);
        % degradation of ACE2 located at iPC via shedding (pmole/h) 
        V_shed_ace2_ipc = p(8) * ACE2_ipc;
        % a term responsible for limitation of COV to cell binding; number COV molecules per cell cannot be higher than Nmax_cov_per_cell due to physical size of a cell and virus which attaches to the cell (UL) 
        steric_factor_ipc = 1 - COV_ACE2_ipc_per_cell / p(19);
        % binding of COV to ACE2 located at iPC surface (pmole/h) 
        V_bind_cov_ace2_ipc = p(9) * (steric_factor_ipc * COV * ACE2_ipc / Kd_cov_ace2 - COV_ACE2_ipc);
        % degradation of ACE2 located at iPC via iPC apoptosis (pmole/h) 
        V_deg_ace2_apo_ipc = p(4) * ACE2_ipc;
        % degradation of COV_ACE2 located at iPC via iPC apoptosis with concomitant COV release (pmole/h) 
        V_deg_cov_ace2_apo_ipc = p(4) * COV_ACE2_ipc;
        % degradation of COV located in iPC via iPC apoptosis (pmole/h) 
        V_deg_cov_apo_ipc = p(4) * COV_ipc;
        % entry of COV into iPC with concomitant ACE2 degradation (pmole/h) 
        V_ent_cov_ipc = p(12) * COV_ACE2_ipc;
        % transition of ACE2 from iPC to vPC with transition of pneumocytes between the states (pmole/h) 
        V_tran_ace2_ipc_vpc = k_tran_ipc_vpc * ACE2_ipc;
        % transition of COV_ACE2 from iPC to vPC with transition of pneumocytes between the states (pmole/h) 
        V_tran_cov_ace2_ipc_vpc = k_tran_ipc_vpc * COV_ACE2_ipc;
        % transition of COV from iPC to vPC with transition of pneumocytes between the states (pmole/h) 
        V_tran_cov_ipc_vpc = k_tran_ipc_vpc * COV_ipc;
        % synthesis of ACE2 by vPC (pmole/h) 
        V_syn_ace2_vpc = p(27) * k_syn_ace2_pc * vPC * Vol_alv * p(1);
        % degradation of ACE2 located at vPC via shedding (pmole/h) 
        V_shed_ace2_vpc = p(8) * ACE2_vpc;
        % a term responsible for limitation of COV to cell binding; number COV molecules per cell cannot be higher than Nmax_cov_per_cell due to physical size of a cell and virus which attaches to the cell (UL) 
        steric_factor_vpc = 1 - COV_ACE2_vpc_per_cell / p(19);
        % binding of COV to ACE2 located at vPC surface (pmole/h) 
        V_bind_cov_ace2_vpc = p(9) * (steric_factor_vpc * COV * ACE2_vpc / Kd_cov_ace2 - COV_ACE2_vpc);
        % degradation of ACE2 located at iPC via vPC apoptosis (pmole/h) 
        V_deg_ace2_apo_vpc = k_apo_vpc * ACE2_vpc;
        % degradation of COV_ACE2 located at vPC via vPC apoptosis with concomitant COV release (pmole/h) 
        V_deg_cov_ace2_apo_vpc = k_apo_vpc * COV_ACE2_vpc;
        % entry of COV into vPC with concomitant ACE2 degradation (pmole/h) 
        V_ent_cov_vpc = p(12) * COV_ACE2_vpc;
        % uncoating of COV in vPC (pmole/h) 
        V_unc_cov_vpc = p(14) * COV_vpc;
        % replication of COV_RNA in vPC (pmole/h) 
        V_rep_cov_rna_vpc = p(15) * COV_RNA_vpc / (1 + (COV_RNA_vpc / (vPC * Vol_alv * p(1)) / p(27)) / p(16));
        % assembling of COV in vPC (pmole/h) 
        V_ass_cov_vpc = p(17) * COV_RNA_vpc;
        % release of COV in vPC (pmole/h) 
        V_rel_cov_vpc = p(13) * COVass_vpc;
        % degradation of COV located in vPC via vPC apoptosis (pmole/h) 
        V_deg_cov_apo_vpc = k_apo_vpc * COV_vpc;
        % degradation of COVass located in vPC via vPC apoptosis with concomitant COV release (pmole/h) 
        V_deg_cov_ass_apo_vpc = k_apo_vpc * COVass_vpc;
        % degradation of COV_RNA located at vPC with concomitant COV_RNA release to bulk phase via vPC apoptosis (pmole/h) 
        V_deg_cov_rna_apo_vpc = k_apo_vpc * COV_RNA_vpc;
        % degradation of COV in bulk phase (pmole/h) 
        V_deg_cov = Vol_alv * p(18) * COV;
        % degradation of COV_RNA in bulk phase (pmole/h) 
        V_deg_cov_rna = Vol_alv * p(20) * COV_RNA;

        if time ~= 0
            shared_values = [time_day, COVass_vpc, Vol_alv, vPC, COVass_vpc_per_cell, COV, COV_RNA, COV_num_sputum_ml, PC, iPC, PC_tot, PC_percent, iPC_percent, vPC_percent, ACE2_pc, ACE2_pc_per_cell, COV_ACE2_pc, COV_ACE2_pc_per_cell, ACE2_pc_per_cell_tot, ACE2_ipc, ACE2_ipc_per_cell, COV_ACE2_ipc, COV_ACE2_ipc_per_cell, ACE2_ipc_per_cell_tot, ACE2_vpc, ACE2_vpc_per_cell, COV_ACE2_vpc, COV_ACE2_vpc_per_cell, ACE2_vpc_per_cell_tot, COV_pc_per_cell_tot, COV_ipc, COV_ipc_per_cell, COV_ipc_per_cell_tot, COV_vpc, COV_vpc_per_cell, COV_RNA_vpc, COV_RNA_vpc_per_cell, COV_vpc_per_cell_tot, COV_sgRNA_perc, PC_hs_ss, V_mat_pc, k_tran_pc_ipc, V_tran_pc_ipc, k_tran_ipc_vpc, V_tran_ipc_vpc, V_apo_pc, V_apo_ipc, switch_ir, IR_apo, k_apo_vpc, V_apo_vpc, ACE2_pc_hs_ss, k_syn_ace2_pc, V_syn_ace2_pc, V_shed_ace2_pc, steric_factor_pc, anti_Ab, VO, Kd_cov_ace2, V_bind_cov_ace2_pc, V_deg_ace2_apo_pc, V_deg_cov_ace2_apo_pc, V_tran_ace2_pc_ipc, V_tran_cov_ace2_pc_ipc, V_syn_ace2_ipc, V_shed_ace2_ipc, steric_factor_ipc, V_bind_cov_ace2_ipc, V_deg_ace2_apo_ipc, V_deg_cov_ace2_apo_ipc, V_deg_cov_apo_ipc, V_ent_cov_ipc, V_tran_ace2_ipc_vpc, V_tran_cov_ace2_ipc_vpc, V_tran_cov_ipc_vpc, V_syn_ace2_vpc, V_shed_ace2_vpc, steric_factor_vpc, V_bind_cov_ace2_vpc, V_deg_ace2_apo_vpc, V_deg_cov_ace2_apo_vpc, V_ent_cov_vpc, V_unc_cov_vpc, V_rep_cov_rna_vpc, V_ass_cov_vpc, V_rel_cov_vpc, V_deg_cov_apo_vpc, V_deg_cov_ass_apo_vpc, V_deg_cov_rna_apo_vpc, V_deg_cov, V_deg_cov_rna];
            OutputFunc(time, y, 'affect');
        end

        %%% recalculated values
        y(1) = 1;
        
    end

    function [res,isterminal,direction] = Conditions(time, y)
        direction = ones(1, 1);
        isterminal = ones(1, 1);
        res = [viral_load_condition(time, y)];     
    end
end
