%%%% This code was generated by heta-compiler of v0.4.29
% 

function [ode_func, out_func, y0_, events_] = out_mrg_Model(p)

    ode_func = @ODEFunc;
    out_func = @OutputFunc;
    y0_ = InitFunc();

    % shared variable
    shared_values = zeros(1, 0);
    integrator = [];

    %%% Initialization of dynamic records
    function y__ = InitFunc()
        integrator = []; % reset integrator

        y__ = [];
    end

    function status = OutputFunc(t, y, flag)
        switch flag
            case 'done'
                assignin('base', 'output', integrator);
            case 'affect'
                integrator(end, :) = shared_values;
            otherwise
                integrator = [integrator; shared_values];
        end
        status = 0;
    end

    function dydt = ODEFunc(t, y)

        dydt = zeros(0, 1);

        %%% Dynamic records annotation

        %%% Output records
        shared_values = [];

        %%% Differential equations
    end

    

    events_ = [];
end