%%%% This code was generated by heta-compiler of v0.6.10
% 

function p = nameless_param()

p = zeros(29, 1);
%%% parameter annotation
p(1) = 1000; % kcell_to_cell, kcell to cell conversion coefficient (cell/kcell) 
p(2) = 602000000000; % NA_pmole, Avogadro constant for 1 pmole (item/pmole) 
p(3) = 0.1; % sputum_dilution_coef, dilution of sputum in comparison with lung epithelium lining fluid (UL) 
p(4) = 0.00082; % k_apo_pc, rate constant of PC and iPC apoptosis (1/h) the value was estimated from the HS submodel at steady state. Indeed, taking into account that (i) PC2 is precursors of PC1 [9227501], (ii) life span of PC1 is about 120 days [20616357], (iii) ratio of PC1/PC2 at steady state = 19/37 [7103258] we represented lung cell  dynamics system as follows: --(Vol_alv*k_mat_pc) --> PC2 --(Vol_alv*k_dif_pc*PC2)--> PC1--(Vol_alv*k_apo_pc1*PC1)-->. Then consider the system at steady state and assuming that lifespan (T_ls) corresponds to time required for 99% of cell die we have come to following formulas: (a) k_apo_pc1 = ln(1/0.01)/(120 days) = 1.6e-3 1/h, (b) k_dif_pc = k_apo_pc1*PC1_ss/PC2_ss = 8.2e-4 1/h, (c) k_mat_pc = k_dif_pc*PC2_ss. Since  PC2 to PC1 transition was not considered in the version of the model we can assume that k_apo_pc = k_dif_pc
p(5) = 0.00082; % kbase_apo_vpc, rate constant of vPC apoptosis (1/h) the value was estimated from [PMID 18487354] only
p(6) = 4; % kbase_tran_pc_ipc, rate constant of PC to iPC transition (1/pM/h) fitted to describe in vivo viral load dynamics
p(7) = 4; % kbase_tran_ipc_vpc, rate constant of iPC to vPC transition (1/pM/h) fitted to describe in vivo viral load dynamics
p(8) = 1.8; % k_shed_ace2_pc, rate constant of ACE2 shedding (1/h) rate constant of shedding catalysed by ADAM17/TACE = 5e-4 1/s
p(9) = 23.56; % k_off_cov_ace2, rate constant of COV_ACE2 complex dissociation (1/h) k_off for viral Spike receptor binding domain (RBD) and ACE2 receptor
p(10) = 150; % Num_sp_per_cov, number of Spike proteins per virion (UL) Basing on estimate  that virion diameter=120-160 nm and Spike height=20nm we have come to following number of Spikes per virion = 4*3.14*(70 nm)^2/(3.14*(10 nm)^2)  = 4*49 = 196. Assuming that "dynamic" diameter of Spike is little bit more we have assumed that there are about  150 spike proteins per 1 virion.
p(11) = 4670; % Kd_spike_ace2, equilibrium dissociation constant of spike (RBD) to ACE2 binding (pM) Kd for viral Spike receptor binding domain (RBD) and ACE2
p(12) = 0.936; % k_ent_cov_ipc, rate constant of COV entry in iPC cell (1/h) estimated on the basis of rate constant of endocytosis for Influenza virus
p(13) = 2; % k_rel_cov_vpc, rate constant of COV release to bulk phase from iPC and vPC cell (1/h) fitted to describe in vivo viral load dynamics averaged across 9 patients
p(14) = 14; % k_unc_cov_vpc, rate constant of COV uncouting in vPC cell (1/h) estimated on the basis of rate constant of endocytosis for Influenza virus: k_end-cyt_Vend in original paper describing release from endosome/uncoating
p(15) = 0.2; % k_rep_cov_rna_vpc, rate constant of COV_RNA replication in vPC cell (1/h) fitted to describe in vivo viral load dynamics averaged across 9 patients
p(16) = 9992; % EC50_rep_cov_rna_vpc, EC50 of COV_RNA replication referring to concentration inindividual vPC cell (pM) it was proposed that a host cell can produce about 8000 (item/cell) virions of Influenza virus before it dies [15384040]. So we have calculated the EC50 basing on the value; taking into account that Vol_pc = 1.33e-12 L/cell we can obtain estimate in pM: EC50 = 8e3 /NA_pmole/Vol_pc = 8e3/6.02e11/1.33e-12 = 9992 pM
p(17) = 0.39; % k_ass_cov_vpc, rate constant of COV assembling in vPC (1/h) fitted to describe in vivo viral load dynamics averaged across 9 patients
p(18) = 0.17; % k_deg_cov, rate constant of COV degradation in bulk phase (1/h) COV half-life on different surfaces and aerosole is varied from 1 to 8 hours. We have chosen half-life equal to 4 hour. So, rate constant is equal to ln2/4 = 0.17 1/h
p(19) = 11900; % Nmax_cov_per_cell, maximal number of viral particles able to be simultaneously attached to pneumocyte (item/cell) maximal number of virions Nmax = (surface area of PC faced to alveoli lumen)/(area of "maximal" section of SARS-CoV-2). Based on PC surface area = 183 um^2 [7103258] and (virion diameter=120-160 nm), one obtains Nmax =  183 um^2 / Pi*(140/2 nm) ^2 = 11900
p(20) = 17; % k_deg_cov_rna, rate constant of COV_RNA degradation in bulk phase (1/h) assumed to be equal to COV half-life equal to 4 hour. So, rate constant is equal to ln2/4 = 0.17 1/h
p(21) = 50; % T_sw_ir, switch on time of IR effect on vPC apoptosis (h) assumed
p(22) = 190; % ET50_ir, Effective Time when IR effect reach 50% of maximal value (h) assumed
p(23) = 700; % Emax_ir_apo, maximal effect of IR on vPC apoptosis (UL) assumed
p(24) = 5; % n_ir, Hill coefficient of IR effect on vPC apoptosis (UL) assumed
p(25) = 14300; % Kd_anti_Ab, Kd for binding of Spike protein and neutralizing antibodies (pM) assumed to be equal to tat presented in the paper for neutralizing mAb
p(26) = 941000; % anti_Ab_max, maximal concentration of anti Spike Ab in serum (pM) For Protective Antigen (PA) for Anthrax vaccine it was measured that concentration of Anti-PA specific IgG in serum is 141.2 ug/mL [15358653]. Taking into account Mr_IgG = 150 kDa, one obtains 141.2 ug/mL =
p(27) = 1.33e-12; % Vol_pc, Volume of Pneumocyte (L/cell) averaged between type I and II pneumocytes (moved to Const)
p(28) = 1000; % L_to_mL,  (mL/L) 
p(29) = 1; % viral_load_,  

end
