%%%% This code was generated by heta-compiler of v0.4.29
% 

function p = out_mrg_Param()

p = zeros(17, 1);
%%% parameter annotation
p(1) = 1000; % kcell_to_cell, kcell to cell conversion coefficient (cell/kcell) 
p(2) = 602000000000; % NA_pmole, Avogadro constant for 1 pmole (item/pmole) 
p(3) = 0.00082; % k_apo_pc, rate constant of PC and iPC apoptosis (1/h) the value was estimated from the HS submodel at steady state. Indeed, taking into account that (i) PC2 is precursors of PC1 [9227501], (ii) life span of PC1 is about 120 days [20616357], (iii) ratio of PC1/PC2 at steady state = 19/37 [7103258] we represented lung cell  dynamics system as follows: --(Vol_alv*k_mat_pc) --> PC2 --(Vol_alv*k_dif_pc*PC2)--> PC1--(Vol_alv*k_apo_pc1*PC1)-->. Then consider the system at steady state and assuming that lifespan (T_ls) corresponds to time required for 99% of cell die we have come to following formulas: (a) k_apo_pc1 = ln(1/0.01)/(120 days) = 1.6e-3 1/h, (b) k_dif_pc = k_apo_pc1*PC1_ss/PC2_ss = 8.2e-4 1/h, (c) k_mat_pc = k_dif_pc*PC2_ss. Since  PC2 to PC1 transition was not considered in the version of the model we can assume that k_apo_pc = k_dif_pc
p(4) = 0.00082; % k_apo_vpc, rate constant of vPC apoptosis (1/h) the value was estimated from [PMID 18487354] only
p(5) = 0.01; % kbase_tran_pc_ipc, rate constant of PC to iPC transition (1/pM/h) fitted to describe in vivo viral load dynamics
p(6) = 0.01; % kbase_tran_ipc_vpc, rate constant of iPC to vPC transition (1/pM/h) fitted to describe in vivo viral load dynamics
p(7) = 1.8; % k_shed_ace2_pc, rate constant of ACE2 shedding (1/h) rate constant of shedding catalysed by ADAM17/TACE = 5e-4 1/s
p(8) = 23.56; % k_off_cov_ace2, rate constant of COV_ACE2 complex dissociation (1/h) k_off for viral Spike receptor binding domain (RBD) and ACE2 receptor
p(9) = 31.13; % Kd_cov_ace2, equilibrium dissociation constant of COV to ACE2 binding (pM) Kd for viral Spike receptor binding domain (RBD) and ACE2 receptor is equal to 4.67 nM. Basing on estimate that virion includes about 150 spike proteins (virion diameter=120-160 nm, Spike height=20nm) we have calculated Kd for COV and ACE2 binding equal to 4.67 nM/150 = 31.13 pM
p(10) = 0.936; % k_ent_cov_ipc, rate constant of COV entry in iPC cell (1/h) estimated on the basis of rate constant of endocytosis for Influenza virus
p(11) = 0.6; % k_rel_cov_ipc, rate constant of COV release to bulk phase from iPC and vPC cell (1/h) fitted to describe in vivo viral load dynamics averaged across 9 patients
p(12) = 14; % k_unc_cov_vpc, rate constant of COV uncouting in vPC cell (1/h) estimated on the basis of rate constant of endocytosis for Influenza virus: k_end-cyt_Vend in original paper describing release from endosome/uncoating
p(13) = 0.6; % k_rep_cov_rna_vpc, rate constant of COV_RNA replication in vPC cell (1/h) fitted to describe in vivo viral load dynamics averaged across 9 patients
p(14) = 10000; % EC50_rep_cov_rna_vpc, EC50 of COV_RNA replication referring to concentration inindividual vPC cell (pM) it was proposed that a host cell can produce about 8000 virions of Influenza virus before it dies. So we have calculated the EC50 basing on the value.
p(15) = 1; % k_ass_cov_vpc, rate constant of COV assembling in vPC (1/h) fitted to describe in vivo viral load dynamics averaged across 9 patients
p(16) = 0.17; % k_deg_cov, rate constant of COV degradation in bulk phase (1/h) COV half-life on different surfaces and aerosole is varied from 1 to 8 hours. We have chosen half-life equal to 4 hour. So, rate constant is equal to ln2/4 = 0.17 1/h
p(17) = 11900; % Nmax_cov_per_cell, maximal number of viral particles able to be simultaneously attached to pneumocyte (item/cell) maximal number of virions Nmax = (surface area of PC faced to alveoli lumen)/(area of "maximal" section of SARS-CoV-2). Based on PC surface area = 183 um^2 [7103258] and (virion diameter=120-160 nm), one obtains Nmax =  183 um^2 / Pi*(140/2 nm) ^2 = 11900

end
