#= 
    This code was generated by heta-compiler 0.6.10
    
=#

__platform__ = (function()

### create default constants
nameless_constants_num_ = NamedTuple{(
  :kcell_to_cell,:NA_pmole,:sputum_dilution_coef,:k_apo_pc,:kbase_apo_vpc,:kbase_tran_pc_ipc,:kbase_tran_ipc_vpc,:k_shed_ace2_pc,:k_off_cov_ace2,:Num_sp_per_cov,:Kd_spike_ace2,:k_ent_cov_ipc,:k_rel_cov_vpc,:k_unc_cov_vpc,:k_rep_cov_rna_vpc,:EC50_rep_cov_rna_vpc,:k_ass_cov_vpc,:k_deg_cov,:Nmax_cov_per_cell,:k_deg_cov_rna,:T_sw_ir,:ET50_ir,:Emax_ir_apo,:n_ir,:Kd_anti_Ab,:anti_Ab_max,:Vol_pc,:L_to_mL,
)}(Float64[
  1000,602000000000,0.1,0.00082,0.00082,4,4,1.8,23.56,150,4670,0.936,2,14,0.2,9992,0.39,0.17,11900,17,50,190,700,5,14300,941000,1.33e-12,1000,
])

### create default observables
nameless_records_output_ = NamedTuple{(
  :time_day,:k_syn_ace2_pc,:k_tran_pc_ipc,:k_tran_ipc_vpc,:VO,:Kd_cov_ace2,:ACE2_pc_per_cell,:COV_ACE2_pc_per_cell,:ACE2_ipc_per_cell,:COV_ACE2_ipc_per_cell,:COV_ipc_per_cell,:ACE2_vpc_per_cell,:COV_ACE2_vpc_per_cell,:COV_vpc_per_cell,:COVass_vpc_per_cell,:COV_RNA_vpc_per_cell,:COV_num_sputum_ml,:PC_tot,:PC_percent,:iPC_percent,:vPC_percent,:ACE2_pc_per_cell_tot,:ACE2_ipc_per_cell_tot,:ACE2_vpc_per_cell_tot,:COV_pc_per_cell_tot,:COV_ipc_per_cell_tot,:COV_vpc_per_cell_tot,:steric_factor_pc,:steric_factor_ipc,:steric_factor_vpc,:COV_sgRNA_perc,:IR_apo,:k_apo_vpc,:switch_ir,:Vol_alv,:PC,:iPC,:vPC,:PC_hs_ss,:ACE2_pc,:ACE2_pc_hs_ss,:COV_ACE2_pc,:ACE2_ipc,:COV_ACE2_ipc,:COV_ipc,:ACE2_vpc,:COV_ACE2_vpc,:COV_vpc,:COV_RNA_vpc,:COV,:COV_RNA,:COVass_vpc,:anti_Ab,:V_mat_pc,:V_tran_pc_ipc,:V_tran_ipc_vpc,:V_apo_pc,:V_apo_ipc,:V_apo_vpc,:V_syn_ace2_pc,:V_shed_ace2_pc,:V_bind_cov_ace2_pc,:V_deg_ace2_apo_pc,:V_deg_cov_ace2_apo_pc,:V_tran_ace2_pc_ipc,:V_tran_cov_ace2_pc_ipc,:V_syn_ace2_ipc,:V_shed_ace2_ipc,:V_bind_cov_ace2_ipc,:V_deg_ace2_apo_ipc,:V_deg_cov_ace2_apo_ipc,:V_deg_cov_apo_ipc,:V_ent_cov_ipc,:V_tran_ace2_ipc_vpc,:V_tran_cov_ace2_ipc_vpc,:V_tran_cov_ipc_vpc,:V_syn_ace2_vpc,:V_shed_ace2_vpc,:V_bind_cov_ace2_vpc,:V_deg_ace2_apo_vpc,:V_deg_cov_ace2_apo_vpc,:V_ent_cov_vpc,:V_unc_cov_vpc,:V_rep_cov_rna_vpc,:V_ass_cov_vpc,:V_rel_cov_vpc,:V_deg_cov_apo_vpc,:V_deg_cov_ass_apo_vpc,:V_deg_cov_rna_apo_vpc,:V_deg_cov,:V_deg_cov_rna,
)}(Bool[
  false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,
])

### create default events
nameless_events_active_ = NamedTuple{(
  :viral_load,
)}(Bool[
  true,
])

### initialization of ODE variables and Records
function nameless_init_func_(cons)
    #(kcell_to_cell,NA_pmole,sputum_dilution_coef,k_apo_pc,kbase_apo_vpc,kbase_tran_pc_ipc,kbase_tran_ipc_vpc,k_shed_ace2_pc,k_off_cov_ace2,Num_sp_per_cov,Kd_spike_ace2,k_ent_cov_ipc,k_rel_cov_vpc,k_unc_cov_vpc,k_rep_cov_rna_vpc,EC50_rep_cov_rna_vpc,k_ass_cov_vpc,k_deg_cov,Nmax_cov_per_cell,k_deg_cov_rna,T_sw_ir,ET50_ir,Emax_ir_apo,n_ir,Kd_anti_Ab,anti_Ab_max,Vol_pc,L_to_mL,) = cons

    # Heta initialize
    t = 0.0 # initial time
    time_day = t / 24.0
    COVass_vpc = 0.0
    vPC = 1.0
    Vol_alv = 0.014
    COVass_vpc_per_cell = cons[2] * COVass_vpc / vPC / Vol_alv / cons[1]
    COV = 0.0018
    COV_RNA = 0.0
    COV_num_sputum_ml = cons[3] * (COV + COV_RNA) * cons[2] / cons[28]
    PC = 2643000000.0
    iPC = 1.0
    PC_tot = PC + iPC + vPC
    PC_percent = 100.0 * PC / PC_tot
    iPC_percent = 100.0 * iPC / PC_tot
    vPC_percent = 100.0 * vPC / PC_tot
    ACE2_pc = 615.0
    ACE2_pc_per_cell = cons[2] * ACE2_pc / PC / Vol_alv / cons[1]
    COV_ACE2_pc = 0.0
    COV_ACE2_pc_per_cell = cons[2] * COV_ACE2_pc / PC / Vol_alv / cons[1]
    ACE2_pc_per_cell_tot = ACE2_pc_per_cell + COV_ACE2_pc_per_cell
    ACE2_ipc = 0.0
    ACE2_ipc_per_cell = cons[2] * ACE2_ipc / iPC / Vol_alv / cons[1]
    COV_ACE2_ipc = 0.0
    COV_ACE2_ipc_per_cell = cons[2] * COV_ACE2_ipc / iPC / Vol_alv / cons[1]
    ACE2_ipc_per_cell_tot = ACE2_ipc_per_cell + COV_ACE2_ipc_per_cell
    ACE2_vpc = 0.0
    ACE2_vpc_per_cell = cons[2] * ACE2_vpc / vPC / Vol_alv / cons[1]
    COV_ACE2_vpc = 0.0
    COV_ACE2_vpc_per_cell = cons[2] * COV_ACE2_vpc / vPC / Vol_alv / cons[1]
    ACE2_vpc_per_cell_tot = ACE2_vpc_per_cell + COV_ACE2_vpc_per_cell
    COV_pc_per_cell_tot = COV_ACE2_pc_per_cell
    COV_ipc = 0.0
    COV_ipc_per_cell = cons[2] * COV_ipc / iPC / Vol_alv / cons[1]
    COV_ipc_per_cell_tot = COV_ACE2_ipc_per_cell + COV_ipc_per_cell
    COV_vpc = 0.0
    COV_vpc_per_cell = cons[2] * COV_vpc / vPC / Vol_alv / cons[1]
    COV_RNA_vpc = 0.0
    COV_RNA_vpc_per_cell = cons[2] * COV_RNA_vpc / vPC / Vol_alv / cons[1]
    COV_vpc_per_cell_tot = COV_ACE2_vpc_per_cell + COV_vpc_per_cell + COV_RNA_vpc_per_cell
    COV_sgRNA_perc = 100.0 * COV_RNA / (COV + COV_RNA)
    PC_hs_ss = 2643000000.0
    V_mat_pc = Vol_alv * cons[4] * PC_hs_ss
    k_tran_pc_ipc = cons[6] * COV_ACE2_pc / Vol_alv
    V_tran_pc_ipc = Vol_alv * k_tran_pc_ipc * PC
    k_tran_ipc_vpc = cons[7] * COV_ipc / Vol_alv
    V_tran_ipc_vpc = Vol_alv * k_tran_ipc_vpc * iPC
    V_apo_pc = Vol_alv * cons[4] * PC
    V_apo_ipc = Vol_alv * cons[4] * iPC
    switch_ir = 0.0
    IR_apo = 1.0 + switch_ir * cons[23] * pow((t / cons[21] - 1.0), cons[24]) / (pow((1.0 + cons[22] / cons[21]), cons[24]) + pow((t / cons[21] - 1.0), cons[24]))
    k_apo_vpc = cons[5] * IR_apo
    V_apo_vpc = Vol_alv * k_apo_vpc * vPC
    ACE2_pc_hs_ss = 615.0
    k_syn_ace2_pc = cons[8] * ACE2_pc_hs_ss / PC_hs_ss / cons[27] / Vol_alv / cons[1]
    V_syn_ace2_pc = cons[27] * k_syn_ace2_pc * PC * Vol_alv * cons[1]
    V_shed_ace2_pc = cons[8] * ACE2_pc
    steric_factor_pc = 1.0 - COV_ACE2_pc_per_cell / cons[19]
    anti_Ab = switch_ir * cons[26] * pow((t / cons[21] - 1.0), cons[24]) / (pow((1.0 + cons[22] / cons[21]), cons[24]) + pow((t / cons[21] - 1.0), cons[24]))
    VO = anti_Ab / (cons[25] + anti_Ab)
    Kd_cov_ace2 = cons[11] / cons[10] / (1.0 - VO)
    V_bind_cov_ace2_pc = cons[9] * (steric_factor_pc * COV * ACE2_pc / Kd_cov_ace2 - COV_ACE2_pc)
    V_deg_ace2_apo_pc = cons[4] * ACE2_pc
    V_deg_cov_ace2_apo_pc = cons[4] * COV_ACE2_pc
    V_tran_ace2_pc_ipc = k_tran_pc_ipc * ACE2_pc
    V_tran_cov_ace2_pc_ipc = k_tran_pc_ipc * COV_ACE2_pc
    V_syn_ace2_ipc = cons[27] * k_syn_ace2_pc * iPC * Vol_alv * cons[1]
    V_shed_ace2_ipc = cons[8] * ACE2_ipc
    steric_factor_ipc = 1.0 - COV_ACE2_ipc_per_cell / cons[19]
    V_bind_cov_ace2_ipc = cons[9] * (steric_factor_ipc * COV * ACE2_ipc / Kd_cov_ace2 - COV_ACE2_ipc)
    V_deg_ace2_apo_ipc = cons[4] * ACE2_ipc
    V_deg_cov_ace2_apo_ipc = cons[4] * COV_ACE2_ipc
    V_deg_cov_apo_ipc = cons[4] * COV_ipc
    V_ent_cov_ipc = cons[12] * COV_ACE2_ipc
    V_tran_ace2_ipc_vpc = k_tran_ipc_vpc * ACE2_ipc
    V_tran_cov_ace2_ipc_vpc = k_tran_ipc_vpc * COV_ACE2_ipc
    V_tran_cov_ipc_vpc = k_tran_ipc_vpc * COV_ipc
    V_syn_ace2_vpc = cons[27] * k_syn_ace2_pc * vPC * Vol_alv * cons[1]
    V_shed_ace2_vpc = cons[8] * ACE2_vpc
    steric_factor_vpc = 1.0 - COV_ACE2_vpc_per_cell / cons[19]
    V_bind_cov_ace2_vpc = cons[9] * (steric_factor_vpc * COV * ACE2_vpc / Kd_cov_ace2 - COV_ACE2_vpc)
    V_deg_ace2_apo_vpc = k_apo_vpc * ACE2_vpc
    V_deg_cov_ace2_apo_vpc = k_apo_vpc * COV_ACE2_vpc
    V_ent_cov_vpc = cons[12] * COV_ACE2_vpc
    V_unc_cov_vpc = cons[14] * COV_vpc
    V_rep_cov_rna_vpc = cons[15] * COV_RNA_vpc / (1.0 + (COV_RNA_vpc / (vPC * Vol_alv * cons[1]) / cons[27]) / cons[16])
    V_ass_cov_vpc = cons[17] * COV_RNA_vpc
    V_rel_cov_vpc = cons[13] * COVass_vpc
    V_deg_cov_apo_vpc = k_apo_vpc * COV_vpc
    V_deg_cov_ass_apo_vpc = k_apo_vpc * COVass_vpc
    V_deg_cov_rna_apo_vpc = k_apo_vpc * COV_RNA_vpc
    V_deg_cov = Vol_alv * cons[18] * COV
    V_deg_cov_rna = Vol_alv * cons[20] * COV_RNA
    
    # save results

    return (
        Float64[
            PC * Vol_alv,
            iPC * Vol_alv,
            vPC * Vol_alv,
            ACE2_pc,
            COV_ACE2_pc,
            ACE2_ipc,
            COV_ACE2_ipc,
            COV_ipc,
            ACE2_vpc,
            COV_ACE2_vpc,
            COV_vpc,
            COV_RNA_vpc,
            COV * Vol_alv,
            COV_RNA * Vol_alv,
            COVass_vpc,
        ],
        Float64[
            switch_ir,
            Vol_alv,
            PC_hs_ss*Vol_alv,
            ACE2_pc_hs_ss,
        ]
    )
end

### calculate RHS of ODE
function nameless_ode_func_(du, u, p, t)
    cons = p.constants
    (switch_ir,Vol_alv,PC_hs_ss_,ACE2_pc_hs_ss,) = p.static
    (PC_,iPC_,vPC_,ACE2_pc,COV_ACE2_pc,ACE2_ipc,COV_ACE2_ipc,COV_ipc,ACE2_vpc,COV_ACE2_vpc,COV_vpc,COV_RNA_vpc,COV_,COV_RNA_,COVass_vpc,) = u 

    # Heta rules
    time_day = t / 24.0
    vPC = vPC_ / Vol_alv
    COVass_vpc_per_cell = cons[2] * COVass_vpc / vPC / Vol_alv / cons[1]
    COV = COV_ / Vol_alv
    COV_RNA = COV_RNA_ / Vol_alv
    COV_num_sputum_ml = cons[3] * (COV + COV_RNA) * cons[2] / cons[28]
    PC = PC_ / Vol_alv
    iPC = iPC_ / Vol_alv
    PC_tot = PC + iPC + vPC
    PC_percent = 100.0 * PC / PC_tot
    iPC_percent = 100.0 * iPC / PC_tot
    vPC_percent = 100.0 * vPC / PC_tot
    ACE2_pc_per_cell = cons[2] * ACE2_pc / PC / Vol_alv / cons[1]
    COV_ACE2_pc_per_cell = cons[2] * COV_ACE2_pc / PC / Vol_alv / cons[1]
    ACE2_pc_per_cell_tot = ACE2_pc_per_cell + COV_ACE2_pc_per_cell
    ACE2_ipc_per_cell = cons[2] * ACE2_ipc / iPC / Vol_alv / cons[1]
    COV_ACE2_ipc_per_cell = cons[2] * COV_ACE2_ipc / iPC / Vol_alv / cons[1]
    ACE2_ipc_per_cell_tot = ACE2_ipc_per_cell + COV_ACE2_ipc_per_cell
    ACE2_vpc_per_cell = cons[2] * ACE2_vpc / vPC / Vol_alv / cons[1]
    COV_ACE2_vpc_per_cell = cons[2] * COV_ACE2_vpc / vPC / Vol_alv / cons[1]
    ACE2_vpc_per_cell_tot = ACE2_vpc_per_cell + COV_ACE2_vpc_per_cell
    COV_pc_per_cell_tot = COV_ACE2_pc_per_cell
    COV_ipc_per_cell = cons[2] * COV_ipc / iPC / Vol_alv / cons[1]
    COV_ipc_per_cell_tot = COV_ACE2_ipc_per_cell + COV_ipc_per_cell
    COV_vpc_per_cell = cons[2] * COV_vpc / vPC / Vol_alv / cons[1]
    COV_RNA_vpc_per_cell = cons[2] * COV_RNA_vpc / vPC / Vol_alv / cons[1]
    COV_vpc_per_cell_tot = COV_ACE2_vpc_per_cell + COV_vpc_per_cell + COV_RNA_vpc_per_cell
    COV_sgRNA_perc = 100.0 * COV_RNA / (COV + COV_RNA)
    PC_hs_ss = PC_hs_ss_ / Vol_alv
    V_mat_pc = Vol_alv * cons[4] * PC_hs_ss
    k_tran_pc_ipc = cons[6] * COV_ACE2_pc / Vol_alv
    V_tran_pc_ipc = Vol_alv * k_tran_pc_ipc * PC
    k_tran_ipc_vpc = cons[7] * COV_ipc / Vol_alv
    V_tran_ipc_vpc = Vol_alv * k_tran_ipc_vpc * iPC
    V_apo_pc = Vol_alv * cons[4] * PC
    V_apo_ipc = Vol_alv * cons[4] * iPC
    IR_apo = 1.0 + switch_ir * cons[23] * pow((t / cons[21] - 1.0), cons[24]) / (pow((1.0 + cons[22] / cons[21]), cons[24]) + pow((t / cons[21] - 1.0), cons[24]))
    k_apo_vpc = cons[5] * IR_apo
    V_apo_vpc = Vol_alv * k_apo_vpc * vPC
    k_syn_ace2_pc = cons[8] * ACE2_pc_hs_ss / PC_hs_ss / cons[27] / Vol_alv / cons[1]
    V_syn_ace2_pc = cons[27] * k_syn_ace2_pc * PC * Vol_alv * cons[1]
    V_shed_ace2_pc = cons[8] * ACE2_pc
    steric_factor_pc = 1.0 - COV_ACE2_pc_per_cell / cons[19]
    anti_Ab = switch_ir * cons[26] * pow((t / cons[21] - 1.0), cons[24]) / (pow((1.0 + cons[22] / cons[21]), cons[24]) + pow((t / cons[21] - 1.0), cons[24]))
    VO = anti_Ab / (cons[25] + anti_Ab)
    Kd_cov_ace2 = cons[11] / cons[10] / (1.0 - VO)
    V_bind_cov_ace2_pc = cons[9] * (steric_factor_pc * COV * ACE2_pc / Kd_cov_ace2 - COV_ACE2_pc)
    V_deg_ace2_apo_pc = cons[4] * ACE2_pc
    V_deg_cov_ace2_apo_pc = cons[4] * COV_ACE2_pc
    V_tran_ace2_pc_ipc = k_tran_pc_ipc * ACE2_pc
    V_tran_cov_ace2_pc_ipc = k_tran_pc_ipc * COV_ACE2_pc
    V_syn_ace2_ipc = cons[27] * k_syn_ace2_pc * iPC * Vol_alv * cons[1]
    V_shed_ace2_ipc = cons[8] * ACE2_ipc
    steric_factor_ipc = 1.0 - COV_ACE2_ipc_per_cell / cons[19]
    V_bind_cov_ace2_ipc = cons[9] * (steric_factor_ipc * COV * ACE2_ipc / Kd_cov_ace2 - COV_ACE2_ipc)
    V_deg_ace2_apo_ipc = cons[4] * ACE2_ipc
    V_deg_cov_ace2_apo_ipc = cons[4] * COV_ACE2_ipc
    V_deg_cov_apo_ipc = cons[4] * COV_ipc
    V_ent_cov_ipc = cons[12] * COV_ACE2_ipc
    V_tran_ace2_ipc_vpc = k_tran_ipc_vpc * ACE2_ipc
    V_tran_cov_ace2_ipc_vpc = k_tran_ipc_vpc * COV_ACE2_ipc
    V_tran_cov_ipc_vpc = k_tran_ipc_vpc * COV_ipc
    V_syn_ace2_vpc = cons[27] * k_syn_ace2_pc * vPC * Vol_alv * cons[1]
    V_shed_ace2_vpc = cons[8] * ACE2_vpc
    steric_factor_vpc = 1.0 - COV_ACE2_vpc_per_cell / cons[19]
    V_bind_cov_ace2_vpc = cons[9] * (steric_factor_vpc * COV * ACE2_vpc / Kd_cov_ace2 - COV_ACE2_vpc)
    V_deg_ace2_apo_vpc = k_apo_vpc * ACE2_vpc
    V_deg_cov_ace2_apo_vpc = k_apo_vpc * COV_ACE2_vpc
    V_ent_cov_vpc = cons[12] * COV_ACE2_vpc
    V_unc_cov_vpc = cons[14] * COV_vpc
    V_rep_cov_rna_vpc = cons[15] * COV_RNA_vpc / (1.0 + (COV_RNA_vpc / (vPC * Vol_alv * cons[1]) / cons[27]) / cons[16])
    V_ass_cov_vpc = cons[17] * COV_RNA_vpc
    V_rel_cov_vpc = cons[13] * COVass_vpc
    V_deg_cov_apo_vpc = k_apo_vpc * COV_vpc
    V_deg_cov_ass_apo_vpc = k_apo_vpc * COVass_vpc
    V_deg_cov_rna_apo_vpc = k_apo_vpc * COV_RNA_vpc
    V_deg_cov = Vol_alv * cons[18] * COV
    V_deg_cov_rna = Vol_alv * cons[20] * COV_RNA
    
    #p.static .= [switch_ir,Vol_alv,PC_hs_ss_,ACE2_pc_hs_ss,]
    du .= [
      V_mat_pc-V_tran_pc_ipc-V_apo_pc,  # dPC_/dt
      V_tran_pc_ipc-V_tran_ipc_vpc-V_apo_ipc,  # diPC_/dt
      V_tran_ipc_vpc-V_apo_vpc,  # dvPC_/dt
      V_syn_ace2_pc-V_shed_ace2_pc-V_bind_cov_ace2_pc-V_deg_ace2_apo_pc-V_tran_ace2_pc_ipc,  # dACE2_pc_/dt
      V_bind_cov_ace2_pc-V_deg_cov_ace2_apo_pc-V_tran_cov_ace2_pc_ipc,  # dCOV_ACE2_pc_/dt
      V_tran_ace2_pc_ipc+V_syn_ace2_ipc-V_shed_ace2_ipc-V_bind_cov_ace2_ipc-V_deg_ace2_apo_ipc-V_tran_ace2_ipc_vpc,  # dACE2_ipc_/dt
      V_tran_cov_ace2_pc_ipc+V_bind_cov_ace2_ipc-V_deg_cov_ace2_apo_ipc-V_ent_cov_ipc-V_tran_cov_ace2_ipc_vpc,  # dCOV_ACE2_ipc_/dt
      -V_deg_cov_apo_ipc+V_ent_cov_ipc-V_tran_cov_ipc_vpc,  # dCOV_ipc_/dt
      V_tran_ace2_ipc_vpc+V_syn_ace2_vpc-V_shed_ace2_vpc-V_bind_cov_ace2_vpc-V_deg_ace2_apo_vpc,  # dACE2_vpc_/dt
      V_tran_cov_ace2_ipc_vpc+V_bind_cov_ace2_vpc-V_deg_cov_ace2_apo_vpc-V_ent_cov_vpc,  # dCOV_ACE2_vpc_/dt
      V_tran_cov_ipc_vpc+V_ent_cov_vpc-V_unc_cov_vpc-V_deg_cov_apo_vpc,  # dCOV_vpc_/dt
      V_unc_cov_vpc+V_rep_cov_rna_vpc-V_ass_cov_vpc-V_deg_cov_rna_apo_vpc,  # dCOV_RNA_vpc_/dt
      -V_bind_cov_ace2_pc+V_deg_cov_ace2_apo_pc-V_bind_cov_ace2_ipc+V_deg_cov_ace2_apo_ipc-V_bind_cov_ace2_vpc+V_deg_cov_ace2_apo_vpc+V_rel_cov_vpc+V_deg_cov_ass_apo_vpc-V_deg_cov,  # dCOV_/dt
      V_deg_cov_rna_apo_vpc-V_deg_cov_rna,  # dCOV_RNA_/dt
      V_ass_cov_vpc-V_rel_cov_vpc-V_deg_cov_ass_apo_vpc,  # dCOVass_vpc_/dt
    ]
end

### output function
function nameless_saving_generator_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (switch_ir,Vol_alv,PC_hs_ss_,ACE2_pc_hs_ss,) = integrator.p.static
        (PC_,iPC_,vPC_,ACE2_pc,COV_ACE2_pc,ACE2_ipc,COV_ACE2_ipc,COV_ipc,ACE2_vpc,COV_ACE2_vpc,COV_vpc,COV_RNA_vpc,COV_,COV_RNA_,COVass_vpc,) = u

        # Heta rules
        time_day = t / 24.0
        vPC = vPC_ / Vol_alv
        COVass_vpc_per_cell = cons[2] * COVass_vpc / vPC / Vol_alv / cons[1]
        COV = COV_ / Vol_alv
        COV_RNA = COV_RNA_ / Vol_alv
        COV_num_sputum_ml = cons[3] * (COV + COV_RNA) * cons[2] / cons[28]
        PC = PC_ / Vol_alv
        iPC = iPC_ / Vol_alv
        PC_tot = PC + iPC + vPC
        PC_percent = 100.0 * PC / PC_tot
        iPC_percent = 100.0 * iPC / PC_tot
        vPC_percent = 100.0 * vPC / PC_tot
        ACE2_pc_per_cell = cons[2] * ACE2_pc / PC / Vol_alv / cons[1]
        COV_ACE2_pc_per_cell = cons[2] * COV_ACE2_pc / PC / Vol_alv / cons[1]
        ACE2_pc_per_cell_tot = ACE2_pc_per_cell + COV_ACE2_pc_per_cell
        ACE2_ipc_per_cell = cons[2] * ACE2_ipc / iPC / Vol_alv / cons[1]
        COV_ACE2_ipc_per_cell = cons[2] * COV_ACE2_ipc / iPC / Vol_alv / cons[1]
        ACE2_ipc_per_cell_tot = ACE2_ipc_per_cell + COV_ACE2_ipc_per_cell
        ACE2_vpc_per_cell = cons[2] * ACE2_vpc / vPC / Vol_alv / cons[1]
        COV_ACE2_vpc_per_cell = cons[2] * COV_ACE2_vpc / vPC / Vol_alv / cons[1]
        ACE2_vpc_per_cell_tot = ACE2_vpc_per_cell + COV_ACE2_vpc_per_cell
        COV_pc_per_cell_tot = COV_ACE2_pc_per_cell
        COV_ipc_per_cell = cons[2] * COV_ipc / iPC / Vol_alv / cons[1]
        COV_ipc_per_cell_tot = COV_ACE2_ipc_per_cell + COV_ipc_per_cell
        COV_vpc_per_cell = cons[2] * COV_vpc / vPC / Vol_alv / cons[1]
        COV_RNA_vpc_per_cell = cons[2] * COV_RNA_vpc / vPC / Vol_alv / cons[1]
        COV_vpc_per_cell_tot = COV_ACE2_vpc_per_cell + COV_vpc_per_cell + COV_RNA_vpc_per_cell
        COV_sgRNA_perc = 100.0 * COV_RNA / (COV + COV_RNA)
        PC_hs_ss = PC_hs_ss_ / Vol_alv
        V_mat_pc = Vol_alv * cons[4] * PC_hs_ss
        k_tran_pc_ipc = cons[6] * COV_ACE2_pc / Vol_alv
        V_tran_pc_ipc = Vol_alv * k_tran_pc_ipc * PC
        k_tran_ipc_vpc = cons[7] * COV_ipc / Vol_alv
        V_tran_ipc_vpc = Vol_alv * k_tran_ipc_vpc * iPC
        V_apo_pc = Vol_alv * cons[4] * PC
        V_apo_ipc = Vol_alv * cons[4] * iPC
        IR_apo = 1.0 + switch_ir * cons[23] * pow((t / cons[21] - 1.0), cons[24]) / (pow((1.0 + cons[22] / cons[21]), cons[24]) + pow((t / cons[21] - 1.0), cons[24]))
        k_apo_vpc = cons[5] * IR_apo
        V_apo_vpc = Vol_alv * k_apo_vpc * vPC
        k_syn_ace2_pc = cons[8] * ACE2_pc_hs_ss / PC_hs_ss / cons[27] / Vol_alv / cons[1]
        V_syn_ace2_pc = cons[27] * k_syn_ace2_pc * PC * Vol_alv * cons[1]
        V_shed_ace2_pc = cons[8] * ACE2_pc
        steric_factor_pc = 1.0 - COV_ACE2_pc_per_cell / cons[19]
        anti_Ab = switch_ir * cons[26] * pow((t / cons[21] - 1.0), cons[24]) / (pow((1.0 + cons[22] / cons[21]), cons[24]) + pow((t / cons[21] - 1.0), cons[24]))
        VO = anti_Ab / (cons[25] + anti_Ab)
        Kd_cov_ace2 = cons[11] / cons[10] / (1.0 - VO)
        V_bind_cov_ace2_pc = cons[9] * (steric_factor_pc * COV * ACE2_pc / Kd_cov_ace2 - COV_ACE2_pc)
        V_deg_ace2_apo_pc = cons[4] * ACE2_pc
        V_deg_cov_ace2_apo_pc = cons[4] * COV_ACE2_pc
        V_tran_ace2_pc_ipc = k_tran_pc_ipc * ACE2_pc
        V_tran_cov_ace2_pc_ipc = k_tran_pc_ipc * COV_ACE2_pc
        V_syn_ace2_ipc = cons[27] * k_syn_ace2_pc * iPC * Vol_alv * cons[1]
        V_shed_ace2_ipc = cons[8] * ACE2_ipc
        steric_factor_ipc = 1.0 - COV_ACE2_ipc_per_cell / cons[19]
        V_bind_cov_ace2_ipc = cons[9] * (steric_factor_ipc * COV * ACE2_ipc / Kd_cov_ace2 - COV_ACE2_ipc)
        V_deg_ace2_apo_ipc = cons[4] * ACE2_ipc
        V_deg_cov_ace2_apo_ipc = cons[4] * COV_ACE2_ipc
        V_deg_cov_apo_ipc = cons[4] * COV_ipc
        V_ent_cov_ipc = cons[12] * COV_ACE2_ipc
        V_tran_ace2_ipc_vpc = k_tran_ipc_vpc * ACE2_ipc
        V_tran_cov_ace2_ipc_vpc = k_tran_ipc_vpc * COV_ACE2_ipc
        V_tran_cov_ipc_vpc = k_tran_ipc_vpc * COV_ipc
        V_syn_ace2_vpc = cons[27] * k_syn_ace2_pc * vPC * Vol_alv * cons[1]
        V_shed_ace2_vpc = cons[8] * ACE2_vpc
        steric_factor_vpc = 1.0 - COV_ACE2_vpc_per_cell / cons[19]
        V_bind_cov_ace2_vpc = cons[9] * (steric_factor_vpc * COV * ACE2_vpc / Kd_cov_ace2 - COV_ACE2_vpc)
        V_deg_ace2_apo_vpc = k_apo_vpc * ACE2_vpc
        V_deg_cov_ace2_apo_vpc = k_apo_vpc * COV_ACE2_vpc
        V_ent_cov_vpc = cons[12] * COV_ACE2_vpc
        V_unc_cov_vpc = cons[14] * COV_vpc
        V_rep_cov_rna_vpc = cons[15] * COV_RNA_vpc / (1.0 + (COV_RNA_vpc / (vPC * Vol_alv * cons[1]) / cons[27]) / cons[16])
        V_ass_cov_vpc = cons[17] * COV_RNA_vpc
        V_rel_cov_vpc = cons[13] * COVass_vpc
        V_deg_cov_apo_vpc = k_apo_vpc * COV_vpc
        V_deg_cov_ass_apo_vpc = k_apo_vpc * COVass_vpc
        V_deg_cov_rna_apo_vpc = k_apo_vpc * COV_RNA_vpc
        V_deg_cov = Vol_alv * cons[18] * COV
        V_deg_cov_rna = Vol_alv * cons[20] * COV_RNA
        
        # force amount
        ACE2_pc_ = ACE2_pc
        ACE2_pc_hs_ss_ = ACE2_pc_hs_ss
        COV_ACE2_pc_ = COV_ACE2_pc
        ACE2_ipc_ = ACE2_ipc
        COV_ACE2_ipc_ = COV_ACE2_ipc
        COV_ipc_ = COV_ipc
        ACE2_vpc_ = ACE2_vpc
        COV_ACE2_vpc_ = COV_ACE2_vpc
        COV_vpc_ = COV_vpc
        COV_RNA_vpc_ = COV_RNA_vpc
        COVass_vpc_ = COVass_vpc
        anti_Ab_ = anti_Ab*Vol_alv

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### TIME EVENTS ###
function nameless_viral_load_tstops_func_(cons, times)
    return [cons[21]]
end

### D EVENTS ###

### STOP EVENTS ###

### event assignments
function nameless_viral_load_affect_func_(integrator)
    cons = integrator.p.constants
    t = integrator.t
    (switch_ir,Vol_alv,PC_hs_ss_,ACE2_pc_hs_ss,) = integrator.p.static
    (PC_,iPC_,vPC_,ACE2_pc,COV_ACE2_pc,ACE2_ipc,COV_ACE2_ipc,COV_ipc,ACE2_vpc,COV_ACE2_vpc,COV_vpc,COV_RNA_vpc,COV_,COV_RNA_,COVass_vpc,) = integrator.u

    # Heta rules
    
    # recalculated values
    (switch_ir,) = (1.0,)
    
    # save results
    integrator.u[[]] = [
    ]
    integrator.p.static[[1,]] = [
        switch_ir,
    ]
end


### MODELS ###

nameless_model_ = (
  nameless_init_func_,
  nameless_ode_func_,
  NamedTuple{(
    :viral_load,
  )}([
    (nameless_viral_load_tstops_func_, nameless_viral_load_affect_func_, :viral_load, false),
  ]),
  NamedTuple{(
  )}([
  ]),
  NamedTuple{(
  )}([
  ]),
  nameless_saving_generator_,
  nameless_constants_num_,
  nameless_events_active_,
  nameless_records_output_
)

### OUTPUT ###

return (
  (
    nameless = nameless_model_,
  ),
  (),
  "0.6.10"
)

end
)()