# This workflow build Heta platform and share results in "dist" branch
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Share

on:
  push:
    branches: [ master, '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [ 8.x ]
        heta-version: [ v0.4.29 ]
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g heta-compiler@${{ matrix.heta-version }}
    - run: heta build -i cov19_life_cycle
    - name: Deploy to "dist" branch
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: dist # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
